// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Client.Computer;
using Content.Shared.Shuttles.Components;
using Content.Shared._NF.Shuttles.Events;
using Content.Shared._Lua.Shuttles.UI;

namespace Content.Client._Lua.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleTabletWindow : FancyWindow, IComputerWindow<ShuttleTabletWindowInterfaceState>
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private ShuttleTabletMode _mode = ShuttleTabletMode.Nav;
    private BoxContainer _weaponsPanel;

    private const int CombatTabletWidth = DefaultTabletWidth + 300;
    private const int DefaultTabletWidth = 960;

    public event Action<NetEntity?, InertiaDampeningMode>? OnInertiaDampeningModeChanged;
    public event Action<NetEntity?, ServiceFlags>? OnServiceFlagsChanged;
    public event Action<NetEntity?, Vector2>? OnSetTargetCoordinates;
    public event Action<NetEntity?, bool>? OnSetHideTarget;

    public event Action? OnWeaponSelectionChanged;
    public event Action? OnFireControlRefresh;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;
    public event Action<List<NetEntity>>? UndockAllRequest;

    private enum ShuttleTabletMode : byte
    {
        Nav,
        Dock
    }

    public ShuttleTabletWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        NavModeButton.OnPressed += _ => SwitchMode(ShuttleTabletMode.Nav);
        DockModeButton.OnPressed += _ => SwitchMode(ShuttleTabletMode.Dock);

        var group = new ButtonGroup();

        NavModeButton.Group = group;
        DockModeButton.Group = group;

        NavModeButton.Pressed = true;

        var rightDisplayNav = NavContainer.FindControl<BoxContainer>("RightDisplayNav");
        var networkPortsPanel = rightDisplayNav.FindControl<PanelContainer>("NetworkPortsPanel");
        networkPortsPanel.Visible = false;

        var ftlLockStripe = DockContainer.FindControl<StripeBack>("FTLLockStripe");
        var ftlLockButtonContainer = DockContainer.FindControl<BoxContainer>("FTLLockButtonContainer");
        ftlLockStripe.Visible = false;
        ftlLockButtonContainer.Visible = false;

        _weaponsPanel = NavContainer.FindControl<BoxContainer>("WeaponsPanel");
        _weaponsPanel.Visible = false;

        NavContainer.Visible = _mode == ShuttleTabletMode.Nav;
        DockContainer.Visible = _mode == ShuttleTabletMode.Dock;

        NavContainer.OnInertiaDampeningModeChanged += (entity, mode) => OnInertiaDampeningModeChanged?.Invoke(entity, mode);
        NavContainer.OnServiceFlagsChanged += (entity, flags) => OnServiceFlagsChanged?.Invoke(entity, flags);
        NavContainer.OnSetTargetCoordinates += (entity, position) => OnSetTargetCoordinates?.Invoke(entity, position);
        NavContainer.OnSetHideTarget += (entity, hide) => OnSetHideTarget?.Invoke(entity, hide);

        NavContainer.OnWeaponSelectionChanged += () => OnWeaponSelectionChanged?.Invoke();
        NavContainer.OnFireControlRefresh += () => OnFireControlRefresh?.Invoke();

        DockContainer.DockRequest += (entity, netEntity) => DockRequest?.Invoke(entity, netEntity);
        DockContainer.UndockRequest += entity => UndockRequest?.Invoke(entity);
        DockContainer.UndockAllRequest += dockEntities => UndockAllRequest?.Invoke(dockEntities);
    }

    public void UpdateState(EntityUid owner, ShuttleTabletWindowInterfaceState cState)
    {
        var shuttle = _entity.GetEntity(cState.Shuttle);
        var linkPower = (int)(cState.LinkPower * 100f);

        _weaponsPanel.Visible = cState.CombatTablet;
        SetWidth = cState.CombatTablet ? CombatTabletWidth : DefaultTabletWidth;

        LinkPower.Text = Loc.GetString("shuttle-tablet-link-power", ("linkPower", linkPower));
        LinkPower.FontColorOverride = linkPower switch
        {
            > 80 => Color.Green,
            > 50 => Color.Yellow,
            > 25 => Color.Orange,
            <= 25 => Color.Red
        };

        NavContainer.SetShuttle(shuttle);
        NavContainer.SetConsole(owner);
        NavContainer.UpdateState(cState.NavState);
        NavContainer.UpdateWeapons(cState.FireControlConnected, cState.FireControllables);

        DockContainer.UpdateState(shuttle, cState.DockState);
    }

    private void SwitchMode(ShuttleTabletMode mode)
    {
        if (_mode == mode)
        {
            return;
        }

        _mode = mode;

        NavContainer.Visible = _mode == ShuttleTabletMode.Nav;
        DockContainer.Visible = _mode == ShuttleTabletMode.Dock;
    }
}
