/*
 * LuaWorld - This file is licensed under AGPLv3
 * Copyright (c) 2025 LuaWorld Contributors
 * See AGPLv3.txt for details.
 */
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._NF.Bank.BUI;
using Content.Shared._Lua.Bank.Events;
using Robust.Client.UserInterface;
using Content.Shared.CartridgeLoader;

namespace Content.Client._Lua.Yupi.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class YupiTransferUiFragment : BoxContainer
{
    private BoundUserInterface _ui = default!;
    private LineEdit _codeInput = default!;
    private LineEdit _amountInput = default!;
    private Label _balance = default!;
    private Button _sendButton = default!;
    private Button _copyCodeButton = default!;
    private Label _lblOwnCodeTitle = default!;
    private Label _lblBalanceTitle = default!;
    private Label _lblTargetCodeTitle = default!;
    private Label _lblAmountTitle = default!;

    public YupiTransferUiFragment()
    {
        RobustXamlLoader.Load(this);
        _codeInput = FindControl<LineEdit>("CodeInput");
        _amountInput = FindControl<LineEdit>("AmountInput");
        _balance = FindControl<Label>("Balance");
        _sendButton = FindControl<Button>("SendButton");
        _copyCodeButton = FindControl<Button>("CopyCodeButton");
        _lblOwnCodeTitle = FindControl<Label>("LblOwnCodeTitle");
        _lblBalanceTitle = FindControl<Label>("LblBalanceTitle");
        _lblTargetCodeTitle = FindControl<Label>("LblTargetCodeTitle");
        _lblAmountTitle = FindControl<Label>("LblAmountTitle");
        _sendButton.OnPressed += _ =>
        {
            if (_ui == null) return;
            if (int.TryParse(_amountInput.Text, out var amount))
            {
                var message = new YupiTransferRequestMessage
                { TargetCode = _codeInput.Text.Trim(), Amount = amount }; _ui.SendMessage(new CartridgeUiMessage(message));
            }
        };

        _copyCodeButton.OnPressed += _ =>
        {
            var text = _copyCodeButton.Text;
            if (!string.IsNullOrEmpty(text)) IoCManager.Resolve<IClipboardManager>().SetText(text);
        };
    }

    public void Initialize(BoundUserInterface ui)
    { _ui = ui; }

    public void UpdateState(YupiTransferUiState state)
    {
        _copyCodeButton.Text = string.IsNullOrWhiteSpace(state.OwnCode) ? "------" : state.OwnCode.ToUpperInvariant();
        _balance.Text = state.Balance.ToString();
        _lblOwnCodeTitle.Text = Loc.GetString("yupi-ui-own-code");
        _lblBalanceTitle.Text = Loc.GetString("yupi-ui-balance");
        _lblTargetCodeTitle.Text = Loc.GetString("yupi-ui-target-code");
        _lblAmountTitle.Text = Loc.GetString("yupi-ui-amount");
        _sendButton.Text = Loc.GetString("yupi-ui-send");
    }
}


