// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Shared._Lua.Starmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class DiskMergerWindow : DefaultWindow
{
    public DiskMergerWindow()
    { RobustXamlLoader.Load(this); }

    public void Update(DiskMergerBuiState state)
    {
        Progress.Visible = true;
        Progress.Value = state.IsMerging ? state.Progress01 : 0f;
        DiskALabel.Text = state.HasDiskA ? $"{Loc.GetString("diskmerger-disk-a")}: {state.DiskAName}" : Loc.GetString("diskmerger-disk-a");
        DiskBLabel.Text = state.HasDiskB ? $"{Loc.GetString("diskmerger-disk-b")}: {state.DiskBName}" : Loc.GetString("diskmerger-disk-b");
        DiskAList.DisposeAllChildren();
        if (state.HasDiskA && state.DiskASectors.Length > 0)
        {
            foreach (var s in state.DiskASectors)
            {
                var display = RenderSectorName(s);
                DiskAList.AddChild(new Label { Text = display, HorizontalAlignment = HAlignment.Left });
            }
        }
        else
        { DiskAList.AddChild(new Label { Text = Loc.GetString("diskmerger-empty"), HorizontalAlignment = HAlignment.Left }); }
        DiskBList.DisposeAllChildren();
        if (state.HasDiskB && state.DiskBSectors.Length > 0)
        {
            foreach (var s in state.DiskBSectors)
            {
                var display = RenderSectorName(s);
                DiskBList.AddChild(new Label { Text = display, HorizontalAlignment = HAlignment.Left });
            }
        }
        else
        { DiskBList.AddChild(new Label { Text = Loc.GetString("diskmerger-empty"), HorizontalAlignment = HAlignment.Left }); }
    }

    private string RenderSectorName(string idOrName)
    {
        switch (idOrName)
        {
            case "FrontierSector": return Loc.GetString("sector-name-FrontierSector");
            case "AsteroidSectorDefault": return Loc.GetString("sector-name-AsteroidSectorDefault");
            case "MercenarySector": return Loc.GetString("sector-name-MercenarySector");
            case "PirateSector": return Loc.GetString("sector-name-PirateSector");
            case "TypanSector": return Loc.GetString("sector-name-TypanSector");
            case "CentCom": return Loc.GetString("sector-name-CentCom");
            default: return idOrName;
        }
    }
}


