// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Shared._Lua.Starmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class PayoutCollectorWindow : DefaultWindow
{
    public event Action? OnClaim;

    public PayoutCollectorWindow()
    {
        RobustXamlLoader.Load(this);
        ClaimButton.OnPressed += _ => OnClaim?.Invoke();
    }

    public void Update(PayoutCollectorBuiState state)
    {
        OwnedLabel.Text = Loc.GetString("payout-owned", ("count", state.OwnedSectors));
        AccumLabel.Text = Loc.GetString("payout-accum", ("amount", state.Accumulated));
    }
}


