// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Shared._Lua.Starmap;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class SectorCaptureWindow : DefaultWindow
{
    public event Action? OnStartCapture;

    public SectorCaptureWindow()
    {
        RobustXamlLoader.Load(this);
        StartButton.OnPressed += _ => OnStartCapture?.Invoke();
    }

    public void Update(SectorCaptureBuiState state)
    {
        Progress.Visible = true;
        Progress.Value = state.IsCapturing ? state.ProgressBar : 0f;
        StartButton.Disabled = state.IsCapturing || !state.CanCapture;
        if (state.IsCapturing)
        { StatusLabel.Text = Loc.GetString("sector-capture-status", ("faction", state.Faction)); }
        else if (!state.CanCapture)
        { StatusLabel.Text = Loc.GetString("sector-capture-not-allowed"); }
        else
        { StatusLabel.Text = Loc.GetString("sector-capture-ready", ("faction", state.Faction)); }
    }
}


