// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaWorld
// See AGPLv3.txt for details.

using Content.Shared._Lua.Starmap;
using Content.Shared.Shuttles.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Content.Shared.Timing;
using Robust.Client.Graphics;

namespace Content.Client._Lua.Starmap;

[GenerateTypedNameReferences]
public sealed partial class StarMapScreen : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;
    private EntityUid? _console;
    private EntityUid? _shuttleEntity;
    private Star? _selectedStar;
    private float _warpRemaining;
    private float _warpTotal;
    private Label? _warpStatusLabel;
    private ProgressBar? _warpBar;
    private StartEndTime _ftlTime;
    private StyleBoxFlat _ftlStyle = new();
    private FTLState _ftlState;

    public StarMapScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _warpStatusLabel = FindControl<Label>("WarpStatusLabel");
        _warpBar = FindControl<ProgressBar>("WarpBar");
        if (_warpBar != null) _warpBar.ForegroundStyleBoxOverride = _ftlStyle;
        StarMapCanvas.OnStarSelect += OnStarSelected;
        WarpButton.OnPressed += _ =>
        { if (_selectedStar.HasValue) RequestWarpToStar?.Invoke(_selectedStar.Value); };
    }

    public event Action<Star>? RequestWarpToStar;

    public void SetConsole(EntityUid? console)
    { _console = console; }

    public void SetShuttle(EntityUid? shuttle)
    { _shuttleEntity = shuttle; }

    public void UpdateState(StarmapConsoleBoundUserInterfaceState state)
    {
        StarMapCanvas.Range = state.Range;
        StarMapCanvas.SetStars(state.Stars);
        StarMapCanvas.SetEdges(state.Edges);
        StarMapCanvas.SetVisibleSectorMaps(state.VisibleSectorMaps);
        StarMapCanvas.SetSectorIdByMap(state.SectorIdByMap);
        StarMapCanvas.SetOwnerByMap(state.OwnerByMap);
        StarMapCanvas.SetSectorColorOverridesHex(state.SectorColorOverrideHexByMap);
        var current = state.Stars.Find(s => s.Position == System.Numerics.Vector2.Zero);
        CurrentStarLabel.Text = Loc.GetString("starmap-current-star", ("name", current.Name));
        if (!_selectedStar.HasValue)
        {
            SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-empty");
            WarpButton.Disabled = true;
        }
        var incomingRemaining = MathF.Max(0, state.WarpCooldownRemainingSeconds);
        if (_warpRemaining > 0 && incomingRemaining > 0) _warpRemaining = MathF.Min(_warpRemaining, incomingRemaining);
        else _warpRemaining = incomingRemaining;
        _warpTotal = MathF.Max(0, state.WarpCooldownTotalSeconds);
        _ftlTime = state.FTLTime;
        _ftlState = state.FTLState;
        switch (state.FTLState)
        {
            case FTLState.Available: _ftlStyle.BackgroundColor = Color.FromHex("#80C71F"); break;
            case FTLState.Starting: _ftlStyle.BackgroundColor = Color.FromHex("#169C9C"); break;
            case FTLState.Travelling: _ftlStyle.BackgroundColor = Color.FromHex("#8932B8"); break;
            case FTLState.Arriving: _ftlStyle.BackgroundColor = Color.FromHex("#F9801D"); break;
            case FTLState.Cooldown: _ftlStyle.BackgroundColor = Color.FromHex("#B02E26"); break;
            default: _ftlStyle.BackgroundColor = Color.FromHex("#B02E26"); break;
        }
        UpdateWarpUI(state);
        if (_selectedStar.HasValue)
        {
            var map = _selectedStar.Value.Map;
            var found = state.Stars.Find(s => s.Map == map);
            if (found.Map != default)
            { OnStarSelected(found); }
            else
            {
                _selectedStar = null;
                SelectedStarLabel.Text = Loc.GetString("starmap-selected-star-empty");
                WarpButton.Disabled = true;
            }
        }
    }

    private void OnStarSelected(Star star)
    {
        _selectedStar = star;
        var name = star.Name;
        if (StarMapCanvas.IsSector(star.Map))
        { SelectedStarLabel.Text = Loc.GetString("starmap-selected-star", ("name", name)); }
        else
        {
            var ownerText = Loc.GetString("starmap-owner-neutral");
            if (StarMapCanvas.TryGetOwner(star.Map, out var owner))
            {
                ownerText = owner switch
                {
                    "Syndicate" => Loc.GetString("starmap-owner-syndicate"),
                    "Nfsd" => Loc.GetString("starmap-owner-nfsd"),
                    "Pirates" => Loc.GetString("starmap-owner-pirates"),
                    _ => Loc.GetString("starmap-owner-neutral")
                };
            }
            var header = Loc.GetString("starmap-selected-star", ("name", name));
            var own = Loc.GetString("starmap-ownership", ("owner", ownerText));
            SelectedStarLabel.Text = $"{header}\n{own}";
        }
        var isCurrent = star.Position == System.Numerics.Vector2.Zero;
        var isAdjacent = StarMapCanvas.IsAdjacentToCurrent(star);
        WarpButton.Disabled = isCurrent || !isAdjacent || _ftlState != FTLState.Available;
    }

    public void Startup()
    { }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _warpRemaining = MathF.Max(0, _warpRemaining - args.DeltaSeconds);
        UpdateWarpUI();
    }

    private void UpdateWarpUI(StarmapConsoleBoundUserInterfaceState? stateOpt = null)
    {
        var seconds = (int)MathF.Ceiling(_warpRemaining);
        var ready = seconds <= 0;
        if (_warpStatusLabel != null)
        {
            var shownState = stateOpt?.FTLState ?? _ftlState;
            if (shownState != FTLState.Available) _warpStatusLabel.Text = Loc.GetString($"shuttle-console-ftl-state-{shownState.ToString()}");
            else
            {
                if (ready)
                { _warpStatusLabel.Text = Loc.GetString("shuttle-console-ftl-state-Available"); }
                else
                {
                    var mins = seconds / 60;
                    var secs = seconds % 60;
                    _warpStatusLabel.Text = mins > 0 ? $"{mins}м {secs:00}с" : $"{secs}s";
                }
            }
        }
        if (_warpBar != null)
        {
            var progress = _ftlTime.ProgressAt(_timing.CurTime);
            if (float.IsFinite(progress)) _warpBar.Value = progress;
            else if (_warpTotal > 0) _warpBar.Value = 1f - MathF.Min(1f, _warpRemaining / _warpTotal);
            else _warpBar.Value = ready ? 1f : 0f;
        }
    }
}
