- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  salary: 70000
  setPreference: true # Lua
  requirements:
  - !type:OverallPlaytimeRequirement #Lua
    time: 36000
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 #2.5 hrs #Lua 2.5<20
  startingGear: ParamedicGear
  alwaysUseSpawner: true
  icon: "JobIconParamedic"
  supervisors: job-supervisors-mmo # Frontier
  displayWeight: 30
  access:
  - Medical
  - Maintenance
  - Paramedic
  accessGroups: # Frontier
  - GeneralAccess # Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Nanotrasen

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
    - EmergencyRollerBedSpawnFolded

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
