using Content.Shared._Mono.Company;
using Content.Shared._Mono.FireControl; // Lua
using Content.Shared._Mono.ShipGuns; // Lua
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Numerics;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    private SharedTransformSystem _xformSystem;

    private EntityUid? _shuttleEntity;

    private double _hudUpdateAccum;
    private const double HudUpdateInterval = 0.2;
    private Vector2? _lastWorldPos;
    private float? _lastDisplayRotDeg;
    private Vector2? _lastLinearVel;
    private float? _lastAngularVelDeg;
    // Lua
    public readonly Dictionary<NetEntity, Button> WeaponsList = new();
    private readonly Dictionary<NetEntity, ShipGunType> _weaponTypes = new();
    public event Action? OnWeaponSelectionChanged;
    public event Action? OnFireControlRefresh;
    // End Lua

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        IFFShuttleToggle.OnToggled += OnIFFShuttleTogglePressed;
        IFFShuttleToggle.Pressed = NavRadar.ShowIFFShuttles;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;
        // Lua
        SelectAllButton.OnPressed += OnSelectAllWeapons;
        UnselectAllButton.OnPressed += OnUnselectAllWeapons;
        SelectBallisticButton.OnPressed += OnSelectBallisticWeapons;
        SelectEnergyButton.OnPressed += OnSelectEnergyWeapons;
        SelectMissileButton.OnPressed += OnSelectMissileWeapons;
        SelectMiningButton.OnPressed += OnSelectMiningWeapons;
        RefreshButton.OnPressed += _ => OnFireControlRefresh?.Invoke();
        // End Lua
        NfInitialize(); // Frontier Initialization for the NavScreen
    }

    // Frontier - IFF search
    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null // If empty, do not filter
            : (entity, grid, iff, labelName) =>
            {
                if (!string.IsNullOrEmpty(labelName) &&
                    labelName.Contains(text, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }

                // Check company name
                if (_entManager.TryGetComponent<CompanyComponent>(entity, out var companyComp) &&
                    !string.IsNullOrEmpty(companyComp.CompanyName))
                {
                    // Try to match the company ID directly
                    if (companyComp.CompanyName.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }

                    // Try to match company name from prototype
                    if (_prototypeManager.TryIndex<CompanyPrototype>(
                        companyComp.CompanyName, out var prototype) &&
                        prototype.Name.Contains(text, StringComparison.OrdinalIgnoreCase))
                    {
                        return true;
                    }
                }

                return false;
            };
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;

        NfAddShuttleDesignation(shuttle); // Frontier - PR #1284 Add Shuttle Designation
    }

    public void SetConsole(EntityUid? console)
    {
        NavRadar.SetConsole(console);
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnIFFShuttleTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFFShuttles ^= true;
        args.Button.Pressed = NavRadar.ShowIFFShuttles;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);

        // Update port names if custom names are available
        UpdateNetworkPortButtonNames(scc.NetworkPortNames);

        NfUpdateState(scc); // Frontier Update State
    }

    /// <summary>
    /// Updates the text on the network port buttons based on the custom port names.
    /// </summary>
    /// <param name="portNames">Dictionary of port IDs to display names</param>
    private void UpdateNetworkPortButtonNames(Dictionary<string, string> portNames)
    {
        // Map of button names to their corresponding port IDs in the component
        var buttonToPortIdMap = new Dictionary<Button, string>
        {
            { DeviceButton1, "device-button-1" },
            { DeviceButton2, "device-button-2" },
            { DeviceButton3, "device-button-3" },
            { DeviceButton4, "device-button-4" },
            { DeviceButton5, "device-button-5" },
            { DeviceButton6, "device-button-6" },
            { DeviceButton7, "device-button-7" },
            { DeviceButton8, "device-button-8" }
        };

        // For each button, check if there's a custom name and update accordingly
        foreach (var (button, portId) in buttonToPortIdMap)
        {
            if (portNames.TryGetValue(portId, out var customName))
            {
                // Use the custom name if available
                button.Text = customName;
            }
            else
            {
                // Otherwise use the default localized name
                var locKey = $"shuttle-console-{portId}";
                button.Text = Loc.GetString(locKey);
            }
        }
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    // Lua
    public void UpdateWeapons(bool connected, FireControllableEntry[]? controllables)
    {
        if (connected)
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-connected");
            ServerStatus.FontColorOverride = Color.Green;
        }
        else
        {
            ServerStatus.Text = Loc.GetString("gunnery-window-disconnected");
            ServerStatus.FontColorOverride = Color.Red;
        }

        if (!connected || controllables == null)
        {
            WeaponsList.Clear();
            ControllablesBox.DisposeAllChildren();
            _weaponTypes.Clear();
            NavRadar.UpdateControllables(Array.Empty<FireControllableEntry>());
            return;
        }
        NavRadar.UpdateControllables(controllables);
        UpdateWeaponsList(controllables);
        UpdateCategoryButtonStates();
    }

    private void UpdateWeaponsList(FireControllableEntry[] controllables)
    {
        var toRemove = new HashSet<NetEntity>(WeaponsList.Keys);
        _weaponTypes.Clear();
        foreach (var controllable in controllables)
        {
            var entity = _entManager.GetEntity(controllable.NetEntity);
            if (_entManager.TryGetComponent<ShipGunTypeComponent>(entity, out var typeComp))
            { _weaponTypes[controllable.NetEntity] = typeComp.Type; }
            if (WeaponsList.TryGetValue(controllable.NetEntity, out _))
            { toRemove.Remove(controllable.NetEntity); }
            else
            {
                var button = new Button
                { ToggleMode = true, Text = controllable.Name, StyleClasses = { "ButtonSquare OpenRight" }, HorizontalExpand = true, Margin = new Thickness(4, 1) };
                button.OnToggled += _ => NotifyWeaponSelectionChanged();
                ControllablesBox.AddChild(button);
                WeaponsList.Add(controllable.NetEntity, button);
            }
        }

        foreach (var netEntity in toRemove)
        {
            if (WeaponsList.TryGetValue(netEntity, out var button))
            {
                ControllablesBox.RemoveChild(button);
                WeaponsList.Remove(netEntity);
            }
        }
        SelectAllButton.Disabled = WeaponsList.Count == 0;
        UnselectAllButton.Disabled = WeaponsList.Count == 0;
    }

    private void UpdateCategoryButtonStates()
    {
        bool hasBallistic = false, hasEnergy = false, hasMissile = false, hasMining = false;
        foreach (var type in _weaponTypes.Values)
        {
            switch (type)
            {
                case ShipGunType.Ballistic: hasBallistic = true; break;
                case ShipGunType.Energy: hasEnergy = true; break;
                case ShipGunType.Missile: hasMissile = true; break;
                case ShipGunType.Mining: hasMining = true; break;
            }
            if (hasBallistic && hasEnergy && hasMissile && hasMining) break;
        }
        SelectBallisticButton.Disabled = !hasBallistic;
        SelectEnergyButton.Disabled = !hasEnergy;
        SelectMissileButton.Disabled = !hasMissile;
        SelectMiningButton.Disabled = !hasMining;
    }
    public List<NetEntity> GetSelectedWeapons()
    {
        var selected = new List<NetEntity>();
        foreach (var (netEntity, button) in WeaponsList)
        { if (button.Pressed) selected.Add(netEntity); }
        return selected;
    }

    private void NotifyWeaponSelectionChanged()
    {
        var selected = new HashSet<NetEntity>();
        foreach (var (netEntity, button) in WeaponsList)
        { if (button.Pressed) selected.Add(netEntity); }
        NavRadar.UpdateSelectedWeapons(selected);
        OnWeaponSelectionChanged?.Invoke();
    }

    private void OnSelectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values) button.Pressed = true;
        NotifyWeaponSelectionChanged();
    }

    private void OnUnselectAllWeapons(BaseButton.ButtonEventArgs args)
    {
        foreach (var button in WeaponsList.Values) button.Pressed = false;
        NotifyWeaponSelectionChanged();
    }

    private void SelectWeaponsByType(ShipGunType targetType)
    {
        foreach (var button in WeaponsList.Values) button.Pressed = false;
        foreach (var (netEntity, button) in WeaponsList)
        { if (_weaponTypes.TryGetValue(netEntity, out var type) && type == targetType) button.Pressed = true; }
        NotifyWeaponSelectionChanged();
    }

    private void OnSelectBallisticWeapons(BaseButton.ButtonEventArgs args) => SelectWeaponsByType(ShipGunType.Ballistic);
    private void OnSelectEnergyWeapons(BaseButton.ButtonEventArgs args) => SelectWeaponsByType(ShipGunType.Energy);
    private void OnSelectMissileWeapons(BaseButton.ButtonEventArgs args) => SelectWeaponsByType(ShipGunType.Missile);
    private void OnSelectMiningWeapons(BaseButton.ButtonEventArgs args) => SelectWeaponsByType(ShipGunType.Mining);

    // End Lua

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _hudUpdateAccum += args.DeltaSeconds;
        if (_hudUpdateAccum < HudUpdateInterval) return;
        _hudUpdateAccum = 0;
        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) || !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        { return; }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);
        var displayRot = (float)(-worldRot.Reduced()).Degrees;
        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = (-worldRot.Reduced()).RotateVec(gridVelocity);
        var angularVelDeg = -MathHelper.RadiansToDegrees(gridBody.AngularVelocity);
        bool posChanged = !_lastWorldPos.HasValue || MathF.Abs(worldPos.X - _lastWorldPos.Value.X) > 0.1f || MathF.Abs(worldPos.Y - _lastWorldPos.Value.Y) > 0.1f;
        bool rotChanged = !_lastDisplayRotDeg.HasValue || MathF.Abs(displayRot - _lastDisplayRotDeg.Value) > 0.1f;
        bool velChanged = !_lastLinearVel.HasValue || MathF.Abs(gridVelocity.X - _lastLinearVel.Value.X) > 0.1f || MathF.Abs(gridVelocity.Y - _lastLinearVel.Value.Y) > 0.1f;
        bool angChanged = !_lastAngularVelDeg.HasValue || MathF.Abs(angularVelDeg - _lastAngularVelDeg.Value) > 0.1f;
        if (posChanged)
        {
            GridPosition.Text = Loc.GetString("shuttle-console-position-value", ("X", $"{worldPos.X:0.0}"), ("Y", $"{worldPos.Y:0.0}"));
            _lastWorldPos = worldPos;
        }
        if (rotChanged)
        {
            GridOrientation.Text = Loc.GetString("shuttle-console-orientation-value", ("angle", $"{displayRot:0.0}"));
            _lastDisplayRotDeg = displayRot;
        }

        if (velChanged)
        {
            GridLinearVelocity.Text = Loc.GetString("shuttle-console-linear-velocity-value",
                ("X", $"{gridVelocity.X + 10f * float.Epsilon:0.0}"),
                ("Y", $"{gridVelocity.Y + 10f * float.Epsilon:0.0}"));
            _lastLinearVel = gridVelocity;
        }

        if (angChanged)
        {
            GridAngularVelocity.Text = Loc.GetString("shuttle-console-angular-velocity-value", ("angularVelocity", $"{angularVelDeg + 10f * float.Epsilon:0.0}"));
            _lastAngularVelDeg = angularVelDeg;
        }
    }
}
