// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Bank.Events;
using Content.Shared._Lua.Bank.UI;
using Content.Shared._Lua.Bank;
using Content.Shared._NF.Bank;

namespace Content.Client._Lua.Bank.UI;

[GenerateTypedNameReferences]
public sealed partial class LuaATMMenu : FancyWindow
{
    public event Action<int>? WithdrawRequest;
    public event Action? DepositRequest;

    private static Color CorruptedColor => new(139, 0, 0, 10);
    private static Color NotCorruptedColor => new(0, 0, 139, 10);

    private bool _enabled;

    private int? _amount;

    public LuaATMMenu()
    {
        RobustXamlLoader.Load(this);

        DepositButton.OnPressed += OnDepositPressed;
        WithdrawButton.OnPressed += OnWithdrawPressed;
        WithdrawEdit.OnTextChanged += OnAmountChanged;
    }

    public void UpdateState(LuaATMMenuInterfaceState state)
    {
        UpdateCorruption(state.Corrupted);
        UpdateDeposit(state.WithdrawOnly, state.Deposit);
    }

    public void UpdatePersonalState(LuaATMPersonalInfoMessage personalState)
    {
        UpdateStatus(personalState.Enabled);
        UpdateBalance(personalState.Balance);
        UpdateYUPICode(personalState.YUPICode);
        UpdateHistory(personalState.History);
    }

    private void UpdateCorruption(bool corrupted)
    {
        var atmNameString = corrupted ? "bank-atm-menu-name-bm" : "bank-atm-menu-name-nt";
        ATMName.Text = Loc.GetString(atmNameString);

        if (ATMNamePanel.PanelOverride is StyleBoxFlat styleBox)
        {
            styleBox.BackgroundColor = corrupted ? CorruptedColor : NotCorruptedColor;
        }
    }

    private void UpdateDeposit(bool withdrawOnly, int amount)
    {
        DepositButton.Disabled = amount <= 0;
        DepositLabel.Text = amount >= 0
        ? BankSystemExtensions.ToSpesoString(amount)
        : Loc.GetString("bank-atm-menu-cash-error");
        DepositContainer.Visible = !withdrawOnly;
    }

    private void UpdateStatus(bool enabled)
    {
        _enabled = enabled;
        WithdrawButton.Disabled = !_enabled;
    }

    private void UpdateBalance(int balance)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(balance);
    }

    private void UpdateYUPICode(string yupiCode)
    {
        YUPICode.Text = string.IsNullOrWhiteSpace(yupiCode)
        ? Loc.GetString("bank-atm-yupi-code-default")
        : yupiCode.ToUpperInvariant();
    }

    private void UpdateHistory(List<BankAccountOperation> history)
    {
        OperationHistoryContainer.RemoveAllChildren();

        if (history.Count == 0)
        {
            var noOperationLabel = new Label
            {
                Text = Loc.GetString("bank-atm-menu-operation-default")
            };

            OperationHistoryContainer.AddChild(noOperationLabel);
            return;
        }

        foreach (var operation in history)
        {
            var typeString = Loc.GetString($"bank-atm-menu-operation-{operation.Type.ToString().ToLower()}");
            var valueString = BankSystemExtensions.ToSpesoString(operation.Value);
            var timeString = operation.Time.ToString(@"hh\:mm\:ss");
            var operationString = Loc.GetString("bank-atm-menu-operation", ("type", typeString), ("value", valueString), ("time", timeString));

            var operationLabel = new Label
            {
                Text = operationString
            };

            OperationHistoryContainer.AddChild(operationLabel);
        }
    }

    private void OnWithdrawPressed(BaseButton.ButtonEventArgs args)
    {
        if (_amount == null)
        {
            return;
        }

        WithdrawRequest?.Invoke(_amount.Value);
    }

    private void OnDepositPressed(BaseButton.ButtonEventArgs args)
    {
        DepositRequest?.Invoke();
    }

    private void OnAmountChanged(LineEdit.LineEditEventArgs args)
    {
        var parsable = int.TryParse(args.Text, out var amount);
        _amount = parsable ? amount : null;
        WithdrawButton.Disabled = !_enabled || !parsable;
    }
}
