using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Client._NF.Shipyard.BUI;
using Content.Shared._NF.Bank;
using Content.Shared._NF.Shipyard.BUI;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared._NF.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects; // Lua
using Robust.Shared.Utility; // Lua
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._NF.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class ShipyardConsoleMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!; // Lua

    public event Action<ButtonEventArgs>? OnSellShip;
    public event Action<ButtonEventArgs>? OnOrderApproved;
    public event Action<ButtonEventArgs>? OnUnassignDeed;
    public event Action<string>? OnRenameShip;
    public event Action<NetEntity?>? OnDockPortSelected; // Lua
    private readonly List<VesselSize> _categoryStrings = new();
    private readonly List<VesselClass> _classStrings = new();
    private readonly List<VesselEngine> _engineStrings = new();
    private VesselSize? _category;
    private VesselClass? _class;
    private VesselEngine? _engine;

    private List<string> _lastAvailableProtos = new();
    private List<string> _lastUnavailableProtos = new();
    private bool _freeListings = false;
    private bool _validId = false;
    private ConfirmButton? _currentlyConfirmingButton = null;

    // Lua start

    private NavInterfaceState? _dockNav;
    private NetEntity? _selectedDockPort;
    private readonly SharedTransformSystem _xform;
    private readonly SpriteSystem _sprite;

    private static readonly ResPath JobIcons = new("/Textures/Interface/Misc/job_icons.rsi");
    private static readonly ResPath NFJobIcons = new("/Textures/_NF/Interface/Misc/job_icons.rsi");
    private static readonly ResPath LuaJobIcons = new("/Textures/_Lua/Interface/Misc/job_icons.rsi");
    private static readonly ResPath LuaShuttleIcons = new("/Textures/_Lua/Interface/Misc/shuttle_icons.rsi");
    private static readonly ResPath ResearchDisciplines = new("/Textures/Interface/Misc/research_disciplines.rsi");

    private static readonly Dictionary<VesselClass, SpriteSpecifier.Rsi> VesselClassRsis = new()
    {
        [VesselClass.Nfsd] = new(NFJobIcons, "nfsdsergeant"),
        [VesselClass.LuaTech] = new(LuaJobIcons, "ops_luatech"),

        [VesselClass.Capital] = new(LuaShuttleIcons, "capital"),
        [VesselClass.Fighter] = new(LuaShuttleIcons, "fighter"),
        [VesselClass.Patrol] = new(LuaShuttleIcons, "patrol"),
        [VesselClass.Pursuit] = new(LuaShuttleIcons, "pursuit"),

        [VesselClass.Expedition] = new(JobIcons, "SecurityPilot"),
        [VesselClass.Scrapyard] = new(LuaShuttleIcons, "scrapyard"),

        [VesselClass.Salvage] = new(JobIcons, "ShaftMiner"),
        [VesselClass.Science] = new(ResearchDisciplines, "experimental"),
        [VesselClass.Cargo] = new(JobIcons, "CargoTechnician"),
        [VesselClass.Chemistry] = new(JobIcons, "Chemist"),
        [VesselClass.Botany] = new(JobIcons, "Botanist"),
        [VesselClass.Engineering] = new(JobIcons, "StationEngineer"),
        [VesselClass.Atmospherics] = new(JobIcons, "AtmosphericTechnician"),
        [VesselClass.Mercenary] = new(LuaJobIcons, "Mercenary"),
        [VesselClass.Medical] = new(JobIcons, "MedicalDoctor"),
        [VesselClass.Paramedical] = new(JobIcons, "Paramedic"),
        [VesselClass.Cryogenic] = new(LuaShuttleIcons, "cryogenic"),
        [VesselClass.Civilian] = new(ResearchDisciplines, "civilianservices"),
        [VesselClass.Kitchen] = new(JobIcons, "Chef"),

        [VesselClass.Syndicate] = new(JobIcons, "NoId"),
        [VesselClass.Pirate] = new(JobIcons, "NoId")
    };

    private static readonly SpriteSpecifier.Rsi VesselClassDefaultRsi = new(JobIcons, "NoId");

    private static readonly Dictionary<VesselEngine, EntProtoId> VesselEngineProtoIds = new()
    {
        [VesselEngine.AME] = "AmeJar",
        [VesselEngine.TEG] = "GeneratorRTG",
        [VesselEngine.Singularity] = "SingularityGenerator",
        [VesselEngine.Solar] = "SolarPanel",
        [VesselEngine.RTG] = "GeneratorRTG",
        [VesselEngine.APU] = "GeneratorWallmountAPU",
        [VesselEngine.Welding] = "PortableGeneratorJrPacmanShuttle",
        [VesselEngine.Plasma] = "FuelPlasma",
        [VesselEngine.Uranium] = "FuelUranium",
        [VesselEngine.Bananium] = "FuelBananium",
        [VesselEngine.Bluespace] = "FuelBluespace"
    };

    private static readonly EntProtoId VesselEngineDefaultProtoId = "MobCat";

    // Lua end

    public ShipyardConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xform = _entManager.System<SharedTransformSystem>(); // Lua
        _sprite = _entManager.System<SpriteSystem>(); // Lua
        Title = Loc.GetString("shipyard-console-menu-title");
        SearchBar.OnTextChanged += OnSearchBarTextChanged;
        Categories.OnItemSelected += OnCategoryItemSelected;
        Classes.OnItemSelected += OnClassItemSelected;
        Engines.OnItemSelected += OnEngineItemSelected;
        SellShipButton.OnPressed += (args) => { OnSellShip?.Invoke(args); };
        UnassignDeedButton.OnPressed += (args) => { OnUnassignDeed?.Invoke(args); };
        RenameButton.OnPressed += OnRenameButtonPressed;

        DockRadar.ShowIFF = false; // Lua
        DockRadar.ShowIFFShuttles = false; // Lua
        DockRadar.ShowDocks = true; // Lua
        DockRadar.OnRadarClick += OnDockRadarClick; // Lua
    }

    public void UpdateDockSelect(NavInterfaceState? nav, NetEntity? selectedPort) // Lua
    {
        if (nav == null)
        {
            _dockNav = null;
            _selectedDockPort = null;
            return;
        }
        _dockNav = nav;
        _selectedDockPort = selectedPort;
        DockRadar.UpdateState(nav);
        DockRadar.HighlightDockPort = selectedPort;
    }

    private void OnDockRadarClick(EntityCoordinates coords) // Lua
    {
        if (_dockNav == null) return;
        var clickMapPos = _xform.ToMapCoordinates(coords).Position;
        NetEntity? best = null;
        var bestDistSq = float.MaxValue;
        foreach (var (_, ports) in _dockNav.Docks)
        {
            foreach (var port in ports)
            {
                var portCoords = _entManager.GetCoordinates(port.Coordinates);
                if (!portCoords.IsValid(_entManager)) continue;
                var portMapPos = _xform.ToMapCoordinates(portCoords).Position;
                var distSq = (portMapPos - clickMapPos).LengthSquared();
                if (distSq < bestDistSq)
                {
                    bestDistSq = distSq;
                    best = port.Entity;
                }
            }
        }
        const float maxPickDistance = 4.0f; // Lua
        if (best == null || bestDistSq > maxPickDistance * maxPickDistance)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            return;
        }
        if (_selectedDockPort.HasValue && best == _selectedDockPort.Value)
        {
            _selectedDockPort = null;
            DockRadar.HighlightDockPort = null;
            OnDockPortSelected?.Invoke(null);
            return;
        }
        _selectedDockPort = best;
        DockRadar.HighlightDockPort = best;
        OnDockPortSelected?.Invoke(best);
    }


    private void OnCategoryItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetCategoryText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnClassItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetClassText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnEngineItemSelected(OptionButton.ItemSelectedEventArgs args)
    {
        SetEngineText(args.Id);
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void OnRenameButtonPressed(ButtonEventArgs args)
    {
        var newName = RenameLineEdit.Text.Trim();
        if (string.IsNullOrEmpty(newName))
            return;

        // Validate length (30 characters max, matching ShuttleDeedComponent.MaxNameLength)
        if (newName.Length > 30)
        {
            newName = newName[..30];
        }

        OnRenameShip?.Invoke(newName);
        RenameLineEdit.Text = "";
    }

    private void OnSearchBarTextChanged(LineEdit.LineEditEventArgs args)
    {
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }

    private void SetCategoryText(int id)
    {
        _category = id == 0 ? null : _categoryStrings[id];
        Categories.SelectId(id);
    }
    private void SetClassText(int id)
    {
        _class = id == 0 ? null : _classStrings[id];
        Classes.SelectId(id);
    }
    private void SetEngineText(int id)
    {
        _engine = id == 0 ? null : _engineStrings[id];
        Engines.SelectId(id);
    }
    /// <summary>
    ///     Populates the list of products that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateProducts(List<string> availablePrototypes, List<string> unavailablePrototypes, bool free, bool canPurchase)
    {
        Vessels.RemoveAllChildren();

        var search = SearchBar.Text.Trim().ToLowerInvariant();

        var newVessels = GetVesselPrototypesFromIds(availablePrototypes);
        AddVesselsToControls(newVessels, search, free, canPurchase);

        var newUnavailableVessels = GetVesselPrototypesFromIds(unavailablePrototypes);
        AddVesselsToControls(newUnavailableVessels, search, free, false);

        _lastAvailableProtos = availablePrototypes;
        _lastUnavailableProtos = unavailablePrototypes;
    }

    /// <summary>
    /// Given a set of prototype IDs, returns a corresponding set of prototypes, ordered by name.
    /// </summary>
    private List<VesselPrototype?> GetVesselPrototypesFromIds(IEnumerable<string> protoIds)
    {
        var vesselList = protoIds.Select(it => _protoManager.TryIndex<VesselPrototype>(it, out var proto) ? proto : null)
            .Where(it => it != null)
            .ToList();

        vesselList.Sort((x, y) =>
            string.Compare(x!.Name, y!.Name, StringComparison.CurrentCultureIgnoreCase));
        return vesselList;
    }

    /// <summary>
    /// Adds all vessels in a given list of prototypes as VesselRows in the UI.
    /// </summary>
    private void AddVesselsToControls(IEnumerable<VesselPrototype?> vessels, string search, bool free, bool canPurchase)
    {
        foreach (var prototype in vessels)
        {
            // Lua start
            if (prototype == null)
            {
                continue;
            }
            // Lua end

            // Filter any ships
            if (_category != null && !prototype.Category.Equals(_category)) // Lua
                continue;
            if (_class != null && !prototype.Classes.Contains(_class.Value)) // Lua
                continue;
            if (_engine != null && !prototype.Engines.Contains(_engine.Value)) // Lua
                continue;
            if (search.Length > 0 && !prototype.Name.ToLowerInvariant().Contains(search)) // Lua
                continue;

            string priceText;
            if (free)
                priceText = Loc.GetString("shipyard-console-menu-listing-free");
            else
                priceText = BankSystemExtensions.ToSpesoString(prototype.Price); // Lua

            // Lua start
            var classRsi = VesselClassDefaultRsi;

            for (var classId = prototype.Classes.Count - 1; classId >= 0; classId--)
            {
                if (VesselClassRsis.TryGetValue(prototype.Classes[classId], out var vesselClassRsi))
                {
                    classRsi = vesselClassRsi;
                    break;
                }
            }

            if (!prototype.Engines.TryGetValue(0, out var vesselEngine)
                || !VesselEngineProtoIds.TryGetValue(vesselEngine, out var engineProtoId))
            {
                engineProtoId = VesselEngineDefaultProtoId;
            }
            // Lua end

            var vesselEntry = new VesselRow
            {
                Vessel = prototype,
                // Lua start
                VesselName = { Text = prototype.Name },
                CategoryLabel = { Text = Loc.GetString($"shipyard-console-category-{prototype.Category}") },
                ClassIcon = { Texture = _sprite.GetState(classRsi).Frame0 },
                EngineIcon = { Texture = _sprite.Frame0(_protoManager.Index(engineProtoId)) },
                // Lua end
                Purchase = { Text = Loc.GetString("shipyard-console-purchase-available"), Disabled = !canPurchase },
                Guidebook = { Disabled = prototype.GuidebookPage is null, TooltipDelay = 0.2f, ToolTip = prototype.Description },
                Price = { Text = priceText },
            };
            vesselEntry.Purchase.OnConfirming += OnStartConfirmingPurchase;
            vesselEntry.Purchase.OnPressed += (args) => { _currentlyConfirmingButton = null; OnOrderApproved?.Invoke(args); };
            Vessels.AddChild(vesselEntry);
        }
    }

    /// <summary>
    /// Confirming handler: ensures that only one button is confirming at a time.
    /// </summary>
    private void OnStartConfirmingPurchase(ButtonEventArgs args)
    {
        if (args.Button is not ConfirmButton confirmButton)
            return;

        if (_currentlyConfirmingButton != null)
            _currentlyConfirmingButton.ClearIsConfirming();
        _currentlyConfirmingButton = confirmButton;
    }

    /// <summary>
    ///     Populates the list categories that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateCategories(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _categoryStrings.Clear();
        Categories.Clear();

        AddCategoriesFromPrototypes(availablePrototypes);
        AddCategoriesFromPrototypes(unavailablePrototypes);

        _categoryStrings.Sort();

        // Add "All" category at the top of the list
        _categoryStrings.Insert(0, VesselSize.All);

        foreach (var str in _categoryStrings)
        {
            Categories.AddItem(Loc.GetString($"shipyard-console-category-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship categories from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddCategoriesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            if (!_categoryStrings.Contains(prototype.Category) && prototype.Category != VesselSize.All)
            {
                _categoryStrings.Add(prototype.Category);
            }
        }
    }

    /// <summary>
    ///     Populates the list classes that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateClasses(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _classStrings.Clear();
        Classes.Clear();

        AddClassesFromPrototypes(availablePrototypes);
        AddClassesFromPrototypes(unavailablePrototypes);

        _classStrings.Sort();

        // Add "All" category at the top of the list
        _classStrings.Insert(0, VesselClass.All);

        foreach (var str in _classStrings)
        {
            Classes.AddItem(Loc.GetString($"shipyard-console-class-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship classes from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddClassesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Classes)
            {
                if (!_classStrings.Contains(cl) && cl != VesselClass.All)
                {
                    _classStrings.Add(cl);
                }
            }
        }
    }

    /// <summary>
    ///     Populates the list engines that will actually be shown, using the current filters.
    /// </summary>
    public void PopulateEngines(List<string> availablePrototypes, List<string> unavailablePrototypes)
    {
        _engineStrings.Clear();
        Engines.Clear();

        AddEnginesFromPrototypes(availablePrototypes);
        AddEnginesFromPrototypes(unavailablePrototypes);

        _engineStrings.Sort();

        // Add "All" category at the top of the list
        _engineStrings.Insert(0, VesselEngine.All);

        foreach (var str in _engineStrings)
        {
            Engines.AddItem(Loc.GetString($"shipyard-console-engine-{str}"));
        }
    }

    /// <summary>
    /// Adds all ship engine power type from a list of vessel prototypes to the current control's list if they are missing.
    /// </summary>
    private void AddEnginesFromPrototypes(IEnumerable<string> prototypes)
    {
        foreach (var protoId in prototypes)
        {
            if (!_protoManager.TryIndex<VesselPrototype>(protoId, out var prototype))
                continue;

            foreach (var cl in prototype.Engines)
            {
                if (!_engineStrings.Contains(cl) && cl != VesselEngine.All)
                {
                    _engineStrings.Add(cl);
                }
            }
        }
    }

    public void UpdateState(ShipyardConsoleInterfaceState state)
    {
        BalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);
        var shipPrice = 0;
        if (!state.FreeListings)
            shipPrice = state.ShipSellValue;

        ShipAppraisalLabel.Text = $"{BankSystemExtensions.ToSpesoString(shipPrice)} ({state.SellRate * 100.0f:F1}%)";
        SellShipButton.Disabled = state.ShipDeedTitle == null;
        UnassignDeedButton.Disabled = state.ShipDeedTitle == null;

        // Show/hide and enable/disable rename controls based on whether there's a ship deed
        var hasShipDeed = state.ShipDeedTitle != null;
        RenameContainer.Visible = hasShipDeed;
        RenameLineEdit.Editable = hasShipDeed;
        RenameButton.Disabled = !hasShipDeed;

        TargetIdButton.Text = state.IsTargetIdPresent
            ? Loc.GetString("id-card-console-window-eject-button")
            : Loc.GetString("id-card-console-window-insert-button");
        NoDeedHelperContainer.Visible = !state.IsTargetIdPresent;
        //DeedContainer.Visible = state.IsTargetIdPresent; // Lua
        if (state.ShipDeedTitle != null)
        {
            DeedTitle.Text = state.ShipDeedTitle;
        }
        else
        {
            DeedTitle.Text = Loc.GetString($"shipyard-console-deed-label-none");
        }
        _freeListings = state.FreeListings;
        _validId = state.IsTargetIdPresent;
        PopulateProducts(_lastAvailableProtos, _lastUnavailableProtos, _freeListings, _validId);
    }
}
