using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared._Wega.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatUiFragment : BoxContainer
{
    public Action? OpenAddContact;
    public Action? OpenDiscovery;
    public Action<bool>? SetVisibleInDiscovery;
    public Action<List<DiscoveryEntry>>? DiscoveryListReceived;
    public Action? OnMutePressed;
    public Action? OpenEmojiPicker;
    public Action<string>? SetActiveChat;
    public Action<string>? SendMessage;
    public Action<string>? EraseChat;
    public Action<string>? CloseChat;
    public Action<string>? LeaveChat;
    public Action? JoinGroup;
    public Action? CreateGroup;

    private NanoChatEmojiPopup? _emojiPopup;
    public string? ActiveChatId;
    public Dictionary<string, ChatContact> Contacts = new();
    public Dictionary<string, ChatGroup> Groups = new();

    public NanoChatUiFragment()
    {
        RobustXamlLoader.Load(this);
        Orientation = LayoutOrientation.Vertical;
        ChatTypeTabs.SetTabTitle(0, Loc.GetString("nano-chat-ui-tab-contacts"));
        ChatTypeTabs.SetTabTitle(1, Loc.GetString("nano-chat-ui-tab-groups"));
        FindContactsButton.OnPressed += _ => OpenDiscovery?.Invoke();
        VisibleInDiscoveryCheckBox.OnToggled += args => SetVisibleInDiscovery?.Invoke(args.Pressed);
        AddContactButton.OnPressed += _ => OpenAddContact?.Invoke();
        JoinGroupButton.OnPressed += _ => JoinGroup?.Invoke();
        CreateGroupButton.OnPressed += _ => CreateGroup?.Invoke();
        MuteChatButton.OnPressed += _ => OnMutePressed?.Invoke();
        InsertStargateButton.OnPressed += _ =>
        {
            const string openTag = "[stargate size=20]";
            const string closeTag = "[/stargate]";
            var insert = openTag + closeTag;
            var pos = MessageInput.CursorPosition;
            var text = MessageInput.Text ?? "";
            MessageInput.Text = text[..pos] + insert + text[pos..];
            MessageInput.CursorPosition = pos + openTag.Length;
        };
        EmojiButton.OnPressed += _ => OpenEmojiPicker?.Invoke();
        SendButton.OnPressed += _ =>
        {
            if (ActiveChatId != null && !string.IsNullOrWhiteSpace(MessageInput.Text))
            {
                SendMessage?.Invoke(MessageInput.Text);
                MessageInput.Text = "";
            }
        };
        EraseChatButton.OnPressed += _ =>
        {
            if (ActiveChatId != null)
            {
                EraseChat?.Invoke(ActiveChatId);
                ActiveChatId = null;
            }
        };
        LeaveChatButton.OnPressed += _ =>
        {
            if (ActiveChatId != null && ActiveChatId.StartsWith("G"))
            {
                LeaveChat?.Invoke(ActiveChatId);
                ActiveChatId = null;
                UpdateUiState();
            }
        };
        CloseChatButton.OnPressed += _ =>
        {
            if (ActiveChatId != null)
            {
                CloseChat?.Invoke(ActiveChatId);
                ActiveChatId = null;
                UpdateUiState();
            }
        };
        MessageInput.OnTextEntered += args =>
        {
            if (ActiveChatId != null && !string.IsNullOrWhiteSpace(args.Text))
            {
                SendMessage?.Invoke(args.Text);
                MessageInput.Text = "";
            }
        };
        ChatTypeTabs.OnTabChanged += _ => OnTabChanged();
        EmojiButton.AddStyleClass(StyleBase.ButtonOpenBoth);
        SendButton.AddStyleClass(StyleBase.ButtonOpenLeft);
        UpdateUiState();
    }

    private void OnTabChanged()
    {
        UpdateContactsList();
    }

    public void UpdateState(NanoChatUiState state)
    {
        OwnIdLabel.Text = state.ChatId;
        Contacts = state.Contacts;
        Groups = state.Groups;
        ActiveChatId = state.ActiveChat;
        VisibleInDiscoveryCheckBox.Pressed = state.VisibleInDiscovery;
        if (state.DiscoveryList != null)
            DiscoveryListReceived?.Invoke(state.DiscoveryList);
        MuteChatButton.TexturePath = state.Muted
            ? "/Textures/_Lua/Interface/soundoff.svg.192dpi"
            : "/Textures/_Lua/Interface/sound.svg.192dpi";
        MuteChatButton.ToolTip = state.Muted
            ? Loc.GetString("nano-chat-ui-unmute-tooltip")
            : Loc.GetString("nano-chat-ui-mute-tooltip");
        UpdateContactsList();
        if (state.ActiveChat != null && state.ActiveChatMessages != null)
        {
            UpdateMessages(state.ActiveChatMessages);
        }
        else
        {
            MessagesContainer.RemoveAllChildren();
        }
        UpdateUiState();
    }

    public void InitializeEmojiPicker()
    {
        _emojiPopup = new NanoChatEmojiPopup();
        _emojiPopup.OnEmojiSelected += emoji =>
        {
            if (ActiveChatId != null)
            {
                MessageInput.Text += emoji;
                MessageInput.CursorPosition = MessageInput.Text.Length;
            }
        };
    }

    public void OpenEmojiPickerInternal()
    {
        if (_emojiPopup == null)
            InitializeEmojiPicker();
        _emojiPopup?.OpenCentered();
    }

    private void UpdateContactsList()
    {
        ContactsContainer.RemoveAllChildren();
        GroupsContainer.RemoveAllChildren();
        NoContactsLabel.Visible = Contacts.Count == 0 && ChatTypeTabs.CurrentTab == 0;
        NoGroupsLabel.Visible = Groups.Count == 0 && ChatTypeTabs.CurrentTab == 1;
        if (ChatTypeTabs.CurrentTab == 0)
        {
            foreach (var contact in Contacts.Values.OrderBy(c => c.ContactName))
            {
                var control = new NanoChatContactControl(contact);
                control.OnPressed += () => SetActiveChat?.Invoke(contact.ContactId);
                ContactsContainer.AddChild(control);
            }
        }
        else
        {
            foreach (var group in Groups.Values.OrderBy(g => g.GroupName))
            {
                var control = new NanoChatGroupControl(group);
                control.OnPressed += () => SetActiveChat?.Invoke(group.GroupId);
                GroupsContainer.AddChild(control);
            }
        }
    }

    private void UpdateMessages(List<ChatMessage> messages)
    {
        MessagesContainer.RemoveAllChildren();
        foreach (var message in messages)
        {
            var messageControl = new NanoChatMessageControl(message);
            MessagesContainer.AddChild(messageControl);
            MessagesContainer.AddChild(new Control { MinSize = new Vector2(0, 4) });
        }
    }

    private void UpdateUiState()
    {
        var hasActiveChat = ActiveChatId != null;
        var isGroupChat = hasActiveChat && ActiveChatId?.StartsWith("G") == true;
        MessageInput.Editable = hasActiveChat;
        MessageInput.PlaceHolder = hasActiveChat
            ? Loc.GetString("nano-chat-ui-message-placeholder")
            : Loc.GetString("nano-chat-ui-select-chat-input");
        InsertStargateButton.Disabled = !hasActiveChat;
        EmojiButton.Disabled = !hasActiveChat;
        SendButton.Disabled = !hasActiveChat;
        EraseChatButton.Visible = hasActiveChat && !isGroupChat;
        LeaveChatButton.Visible = hasActiveChat && isGroupChat;
        CloseChatButton.Visible = hasActiveChat;
        if (ActiveChatId != null)
        {
            if (isGroupChat && Groups.TryGetValue(ActiveChatId, out var group))
            {
                ChatTitle.Text = $"{group.GroupName} {ActiveChatId}";
            }
            else if (!isGroupChat && Contacts.TryGetValue(ActiveChatId, out var contact))
            {
                ChatTitle.Text = contact.ContactName;
            }
            else
            {
                ChatTitle.Text = Loc.GetString("nano-chat-ui-unknown-chat");
            }
        }
        else
        {
            ChatTitle.Text = Loc.GetString("nano-chat-ui-select-chat");
            MessagesContainer.RemoveAllChildren();
        }
    }
}
