using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatEmojiPopup : DefaultWindow
{
    public Action<string>? OnEmojiSelected;

    private static readonly string[] Emojis = new[]
    {
        "\u2665", "\u2605", "\u2606", "\u269D", "\u269C", "\u269A", "\u269B", "\u267B",
        "\u262E", "\u262F", "\u2623", "\u2622", "\u2620", "\u267F", "\u2695", "\u26A7",
        "\u2190", "\u2192", "\u2191", "\u2193", "\u2194", "\u2195", "\u2196", "\u2197",
        "\u2198", "\u2199", "\u2302", "\u2303", "\u2304",
        "\u00B1", "\u00D7", "\u00F7", "\u2248", "\u2260", "\u2261", "\u2264", "\u2265",
        "\u221A", "\u221E", "\u222B", "\u2202", "\u2206", "\u2318", "\u2325", "\u2326",
        "\u232B", "\u238B", "\u23CE", "\u2324", "\u2327",
        "\u231A", "\u23F1", "\u23F2", "\u23F3", "\u231B",
        "\uD83D\uDD50", "\uD83D\uDD51", "\uD83D\uDD52", "\uD83D\uDD53", "\uD83D\uDD54",
        "\uD83D\uDD55", "\uD83D\uDD56", "\uD83D\uDD57", "\uD83D\uDD58", "\uD83D\uDD59",
        "\uD83D\uDD5A", "\uD83D\uDD5B", "\uD83D\uDD5C", "\uD83D\uDD5D", "\uD83D\uDD5E", "\uD83D\uDD5F",
        "\u2600", "\u2601", "\u2602", "\u2603", "\u2744", "\u26A1", "\u2604", "\uD83C\uDF0D",
        "\uD83C\uDF0E", "\uD83C\uDF0F", "\uD83C\uDF15", "\u2B50",
        "\u25CF", "\u25CB", "\u25C6", "\u25C7", "\u25A0", "\u25A1", "\u25B2", "\u25B3",
        "\u25BC", "\u25BD", "\u25B6", "\u25B7", "\u25C0", "\u25C1", "\u2605", "\u2606",
        "\u2610", "\u2611", "\u2612", "\u25AA", "\u25AB", "\u25CA", "\u25E6", "\u25CC",
        "\u266A", "\u266B", "\u266C", "\uD83C\uDFA7",
        "\u2660", "\u2663", "\u2665", "\u2666", "\u2664", "\u2667", "\u2661", "\u2662",
        "\u2654", "\u2655", "\u2656", "\u2657", "\u2658", "\u2659", "\u265A", "\u265B",
        "\u265C", "\u265D", "\u265E", "\u265F", "\uD83C\uDFAE", "\uD83D\uDD79",
        "\u2709", "\uD83D\uDCE4", "\uD83D\uDCE5", "\uD83D\uDCE6", "\uD83D\uDCEB",
        "\uD83D\uDCEA", "\uD83D\uDCEC", "\uD83D\uDCED", "\u270F", "\u2712",
        "\uD83D\uDCF7", "\uD83D\uDCB0",
        "\uD83D\uDECE", "\uD83D\uDE91", "\uD83D\uDE92", "\uD83D\uDE8D", "\uD83D\uDE94", "\u2693", "\u2708", "\uD83D\uDE29",
        "\uD83C\uDF36", "\uD83C\uDF78",
        "\uD83D\uDC26", "\uD83D\uDD77", "\uD83D\uDC1F", "\uD83D\uDC15", "\uD83D\uDC08", "\uD83E\uDDB6", "\uD83D\uDD4A", "\uD83D\uDC3F",
        "\uD83E\uDDF5", "\u2618", "\uD83E\uDDE8", "\uD83C\uDF1C",
        "\u2639", "\uD83D\uDE10", "\uD83D\uDC7D",
        "\uD83D\uDD90", "\u270B", "\uD83D\uDC4C", "\u270C", "\uD83D\uDC48", "\uD83D\uDC49", "\uD83D\uDC46", "\uD83D\uDC47",
        "\u261D", "\uD83D\uDC4D", "\uD83D\uDC4E", "\u270D", "\uD83D\uDC42", "\uD83D\uDC41", "\u26F7", "\uD83C\uDFC2",
        "\uD83C\uDFCC", "\uD83C\uDFC4", "\uD83C\uDFCA", "\u26F9", "\uD83C\uDFCB", "\uD83E\uDD2A", "\uD83D\uDC63", "\uD83E\uDDC2",
        "\uD83C\uDF21", "\uD83E\uDDE8", "\uD83E\uDDE9", "\uD83E\uDDEA", "\uD83D\uDCBA", "\uD83D\uDCBB", "\uD83C\uDF0D", "\uD83D\uDED4",
        "\u26F0", "\uD83D\uDED5", "\uD83D\uDED6", "\uD83D\uDED6", "\uD83D\uDED7", "\uD83D\uDED9", "\uD83D\uDEDE", "\uD83D\uDEDB", "\uD83D\uDED7",
        "\uD83E\uDDE8", "\uD83E\uDDF5", "\uD83D\uDED6", "\uD83D\uDED8", "\uD83D\uDEDA", "\uD83D\uDEDC", "\uD83D\uDEDD", "\uD83D\uDEDD", "\u26EA",
        "\uD83D\uDED5", "\u26E9", "\u26F2", "\uD83C\uDF19", "\u2668", "\uD83D\uDECE", "\u2602", "\uD83D\uDC53",
        "\uD83D\uDC36", "\uD83E\uDDE1", "\uD83E\uDDE2", "\uD83E\uDDE3", "\uD83D\uDEDD", "\uD83E\uDD32", "\uD83C\uDF93", "\u26D1",
        "\uD83D\uDD12", "\uD83D\uDD08", "\uD83D\uDD09", "\uD83D\uDD0A", "\uD83C\uDF99", "\uD83C\uDF9A", "\uD83C\uDF9B", "\uD83C\uDFA7",
        "\uD83D\uDCFB", "\u260E", "\uD83D\uDCEF", "\uD83C\uDFBB", "\uD83D\uDDA5", "\uD83D\uDDA8", "\u2328", "\uD83D\uDDB1", "\uD83D\uDDB2", "\uD83C\uDFBD"
    };

    public NanoChatEmojiPopup()
    {
        RobustXamlLoader.Load(this);
        foreach (var emoji in Emojis)
        {
            var button = new Button
            {
                Text = emoji,
                MinSize = new Vector2(40, 40),
                HorizontalExpand = true
            };
            button.OnPressed += _ =>
            {
                OnEmojiSelected?.Invoke(emoji);
                Close();
            };
            EmojiContainer.AddChild(button);
        }
    }

    public void Show(Action<string> onSelect)
    {
        OnEmojiSelected = onSelect;
        OpenCentered();
    }
}
