using Content.Shared._Wega.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatDiscoveryPopup : DefaultWindow
{
    public Action<string, string>? OnAddContact;

    public NanoChatDiscoveryPopup()
    {
        RobustXamlLoader.Load(this);
        CancelButton.OnPressed += _ => Close();
    }

    public void SetEntries(IReadOnlyList<DiscoveryEntry> entries)
    {
        EntriesContainer.RemoveAllChildren();
        EmptyLabel.Visible = entries.Count == 0;
        foreach (var entry in entries)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true
            };
            row.AddChild(new Label
            {
                Text = $"{entry.DisplayName} ({entry.ChatId})",
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            });
            var addBtn = new Button { Text = Loc.GetString("nano-chat-ui-add") };
            var chatId = entry.ChatId;
            var displayName = entry.DisplayName;
            addBtn.OnPressed += _ =>
            {
                OnAddContact?.Invoke(chatId, displayName);
                Close();
            };
            row.AddChild(addBtn);
            EntriesContainer.AddChild(row);
        }
    }
}
