using Content.Client._Lua.Stargate;
using Content.Client.UserInterface.RichText;
using Content.Shared._Wega.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.RichText;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Wega.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NanoChatMessageControl : Control
{
    private static readonly Type[] AllowedTags =
    [
        typeof(BoldItalicTag),
        typeof(BoldTag),
        typeof(BulletTag),
        typeof(ColorTag),
        typeof(HeadingTag),
        typeof(ItalicTag),
        typeof(MonoTag),
        typeof(StargateGlyphTag)
    ];

    public NanoChatMessageControl(ChatMessage message)
    {
        RobustXamlLoader.Load(this);
        MessageText.SetMessage(FormattedMessage.FromMarkupPermissive(message.Message), AllowedTags, null);
        SenderName.Text = message.SenderName;
        TimeLabel.Text = message.Timestamp.ToString(@"hh\:mm");
        if (message.IsOwnMessage)
        {
            MessageContainer.HorizontalAlignment = HAlignment.Right;
            HeaderContainer.HorizontalAlignment = HAlignment.Right;
            if (!message.Delivered)
            {
                MessageText.ModulateSelfOverride = Color.Red;
            }
        }
        else
        {
            MessageContainer.HorizontalAlignment = HAlignment.Left;
            HeaderContainer.HorizontalAlignment = HAlignment.Left;
        }
    }
}
