// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Stargate;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
namespace Content.Client._Lua.Stargate;
[GenerateTypedNameReferences]
public sealed partial class StargateMinimapTabletWindow : FancyWindow
{
    public event Action<Vector2, string?>? OnMarkerPlaced;
    public event Action<int>? OnMarkerRemoved;
    public event Action<int, int>? OnMergeDisk;
    private readonly StargateMinimapControl _map;
    private List<StargateMinimapMarker> _currentMarkers = new();
    public StargateMinimapTabletWindow()
    {
        RobustXamlLoader.Load(this);
        Disk1Label.Text = Loc.GetString("stargate-minimap-disk-empty");
        Disk2Label.Text = Loc.GetString("stargate-minimap-disk-empty");
        MergeTo2Button.Text = Loc.GetString("stargate-minimap-merge-1-to-2");
        MergeTo1Button.Text = Loc.GetString("stargate-minimap-merge-2-to-1");
        StatusLabel.Text = Loc.GetString("stargate-minimap-status");
        _map = new StargateMinimapControl();
        MapPanel.AddChild(_map);
        _map.OnMapClick += pos => OnMarkerPlaced?.Invoke(pos, null);
        _map.OnMarkerRemove += idx => OnMarkerRemoved?.Invoke(idx);
        MergeTo2Button.OnPressed += _ => OnMergeDisk?.Invoke(1, 2);
        MergeTo1Button.OnPressed += _ => OnMergeDisk?.Invoke(2, 1);
    }
    public void UpdateState(StargateMinimapUiState state)
    {
        _map.UpdateState(state);
        Disk1Label.Text = state.HasDisk1 ? Loc.GetString("stargate-minimap-disk-active") : Loc.GetString("stargate-minimap-disk-empty");
        Disk2Label.Text = state.HasDisk2 ? Loc.GetString("stargate-minimap-disk-ready") : Loc.GetString("stargate-minimap-disk-empty");
        MergeTo2Button.Disabled = !state.HasDisk1 || !state.HasDisk2;
        MergeTo1Button.Disabled = !state.HasDisk1 || !state.HasDisk2;
        _currentMarkers = state.Markers;
    }
}
