# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: OutpostTypanCargotech
  name: job-name-typan-cargotech
  playTimeTracker: JobOutpostSyndicateCargotech
  salary: 35000
  description: Карготехник из далёкого космоса.
  startingGear: SyndicateCargotech
  icon: "JobIconOutpostTypanCargotech"
  supervisors: job-supervisors-typan-telecommunications-officer
  canBeAntag: false
  hideConsoleVisibility: true
  requirements:
  - !type:RoleTimeRequirement
    role: JobPilot
    time: 36000 # 20h
  - !type:RoleTimeRequirement
    role: JobPassenger
    time: 36000 # 20h
  - !type:RoleTimeRequirement
    role: JobFrontierEngineer
    time: 36000 # 20h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 20h
  access:
  - SyndicateAgent
  - NuclearOperative
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ DeathAcidifierImplantLWTypan ]
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Syndicate
      - type: SpecialSectorStationRecord
        recordGeneration: FalseRecord
      - type: MailDisabled
      - type: NpcFactionMember
        factions:
        - LuaNordFoll
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNordfoll ]

- type: startingGear
  id: SyndicateCargotech
  equipment:
    ears: ClothingHeadsetAltOutpostTypan
    jumpsuit: ClothingUniformJumpsuitOutpostTypanCargotech
    back: ClothingBackpackSyndicateFilled
    shoes: ClothingShoesBootsCombatOutpostTypan
    id: SyndiPDACargo

- type: chameleonOutfit
  id: OutpostTypanCargotechChameleonOutfit
  job: OutpostTypanCargotech
  equipment:
    jumpsuit: ClothingUniformJumpsuitOutpostTypanCargotech
