// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Shared._Lua.SponsorPlayer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using System.Linq;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Lua.SponsorPlayer;

[GenerateTypedNameReferences]
public sealed partial class SponsorPlayerMenu : FancyWindow
{
    public event Action<bool>? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action? OnPreviousPressed;
    public event Action? OnNextPressed;
    public event Action<bool>? OnRepeatToggled;
    public event Action<float>? OnVolumeChanged;
    private string? _selectedTrackId;
    private string? _currentTrackId;
    private string? _currentTrackHash;
    private string? _currentTrackTitle;
    private bool _isPlaying;
    private List<SponsorTrackInfo> _allTracks = new();
    public SponsorPlayerMenu()
    {
        RobustXamlLoader.Load(this);
        TrackList.OnItemSelected += args =>
        {
            if (TrackList[args.ItemIndex].Metadata is string trackId)
            {
                _selectedTrackId = trackId;
                UpdateTransportState();
            }
        };

        PlayButton.OnPressed += _ =>
        {
            var selectedDifferentTrack = _selectedTrackId != null && _selectedTrackId != _currentTrackId;
            if (_isPlaying && !selectedDifferentTrack)
            {
                OnPlayPressed?.Invoke(false);
                return;
            }
            if (GetPlayableTrackId() != null) OnPlayPressed?.Invoke(true);
        };
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        PreviousButton.OnPressed += _ => OnPreviousPressed?.Invoke();
        NextButton.OnPressed += _ => OnNextPressed?.Invoke();
        RepeatButton.OnToggled += args =>
        { OnRepeatToggled?.Invoke(args.Pressed); };
        SearchBar.OnTextChanged += _ => ApplyFilter();
        VolumeSlider.OnValueChanged += range =>
        {
            var uiValue = 100f - (float)range.Value;
            var volume = uiValue / 100f;
            VolumeValueLabel.Text = $"{(int)uiValue}%";
            OnVolumeChanged?.Invoke(volume);
        };
        SetVolumeSlider(1f);
        UpdateTransportState();
    }

    public void PopulateTracks(List<SponsorTrackInfo> tracks)
    {
        _allTracks = tracks;
        if (tracks.Count == 0)
        {
            StatusLabel.Text = Loc.GetString("sponsor-player-no-tracks");
            TrackList.Clear();
            UpdateTransportState();
            return;
        }
        StatusLabel.Text = Loc.GetString("sponsor-player-track-count", ("count", tracks.Count));
        ApplyFilter();
    }

    public void ShowError(string locKey)
    {
        _allTracks = new();
        TrackList.Clear();
        _selectedTrackId = null;
        StatusLabel.Text = Loc.GetString(locKey);
        UpdateTransportState();
    }

    public void SetNowPlaying(string? title)
    { SongName.Text = string.IsNullOrEmpty(title) ? "---" : title; }

    public void SetCurrentTrack(string? trackId, string? trackHash, string? title)
    {
        var previousCurrentTrackId = _currentTrackId;
        _currentTrackId = trackId;
        _currentTrackHash = trackHash;
        _currentTrackTitle = title;
        if (_selectedTrackId == null || _selectedTrackId == previousCurrentTrackId) _selectedTrackId = trackId;
        SetNowPlaying(title);
        SelectTrackInVisibleList(_selectedTrackId ?? _currentTrackId);
        UpdateTransportState();
    }

    public void SetIsPlaying(bool playing)
    {
        _isPlaying = playing;
        PlayButton.ToolTip = Loc.GetString(playing ? "sponsor-player-button-stop" : "sponsor-player-button-play");
        UpdateTransportState();
    }

    public void SetRepeatEnabled(bool enabled)
    { RepeatButton.Pressed = enabled; }

    public void SetVolumeSlider(float volume)
    {
        var clamped = Math.Clamp(volume, 0f, 1f);
        var uiValue = clamped * 100f;
        VolumeSlider.SetValueWithoutEvent(100f - uiValue);
        VolumeValueLabel.Text = $"{(int) uiValue}%";
    }

    public string? GetSelectedTrackId() => _selectedTrackId;

    public string? GetSelectedTrackTitle()
    { return _allTracks.FirstOrDefault(t => t.Id == _selectedTrackId)?.Title; }
    public string? GetPlayableTrackId()
    { return _selectedTrackId ?? _currentTrackId; }
    public string? GetPlayableTrackTitle()
    { return _allTracks.FirstOrDefault(t => t.Id == GetPlayableTrackId())?.Title ?? _currentTrackTitle; }
    public string? GetPlayableTrackHash()
    { return _allTracks.FirstOrDefault(t => t.Id == GetPlayableTrackId())?.Hash ?? _currentTrackHash; }

    private void ApplyFilter()
    {
        var filter = SearchBar.Text?.Trim() ?? string.Empty;
        var filtered = string.IsNullOrEmpty(filter) ? _allTracks : _allTracks.FindAll(t => t.Title.Contains(filter, StringComparison.OrdinalIgnoreCase));
        TrackList.Clear();
        foreach (var track in filtered)
        { TrackList.AddItem(track.Title, metadata: track.Id); }
        SelectTrackInVisibleList(_selectedTrackId ?? _currentTrackId);
        UpdateTransportState();
    }

    private void UpdateTransportState()
    {
        var hasPlayableTrack = GetPlayableTrackId() != null;
        var hasAnyTracks = _allTracks.Count > 0;
        PlayButton.Disabled = !_isPlaying && !hasPlayableTrack;
        StopButton.Disabled = !_isPlaying;
        PreviousButton.Disabled = !hasAnyTracks;
        NextButton.Disabled = !hasAnyTracks;
    }

    private void SelectTrackInVisibleList(string? trackId)
    {
        _selectedTrackId = null;
        if (trackId == null) return;
        for (var i = 0; i < TrackList.Count; i++)
        {
            if (!Equals(TrackList[i].Metadata, trackId)) continue;
            _selectedTrackId = trackId;
            TrackList[i].Selected = true;
            return;
        }
    }
}
