- type: entity
  name: firealoe
  id: FoodFireAloe
  description: IT BURNS!! IT BURNS!!!
  parent: ProduceBase
  components:
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      FoodFireAloe: 100
  - type: Stack
    stackType: FoodFireAloe
    count: 1
  - type: Sprite
    sprite: _Lua/Objects/Specific/Hydroponics/firealoe.rsi
  - type: Item
    size: Small
    sprite: _Lua/Objects/Specific/Hydroponics/firealoe.rsi
    heldPrefix: produce
  - type: MeleeWeapon
    damage:
      types:
        Heat: 5
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 20
        reagents:
        - ReagentId: Pyrazine
          Quantity: 5
        - ReagentId: Leporazine
          Quantity: 5
  - type: IgniteOnMeleeHit
    fireStacks: 2
  - type: DamageOnHoldingAliveOnly  #  чтобы пакостники не ложили в руки трупами и не стакали по миллион урона
    damage:
      types:
        Heat: 1
    interval: 0.1
    ignoreResistances: true
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 15
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          path: /Audio/Effects/burning.ogg
      - !type:DoActsBehavior
        acts: [ "Destruction" ] 
  - type: DamageOnHit # как у гитары вообщем... только через 3 удара ломается.
    damage:
      types:
        Heat: 5
  - type: Damageable
    damageContainer: Inorganic
  - type: Produce
    seedId: firealoe

- type: entity
  name: mint
  description: Освежает.
  parent: FoodProduceBase
  id: FoodMint
  components:
  - type: Sprite
    sprite: _Lua/Objects/Specific/Hydroponics/mint.rsi
    state: produce
  - type: Item
    heldPrefix: produce
  - type: Produce
    seedId: mint
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 5
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: Cryoxadone
          Quantity: 2
  - type: Tag
    tags:
    - Fruit

- type: entity
  name: juniper
  description: Известно ли вам то, что в можжевельнике в небольших дозировках имеется фенол?
  parent: FoodProduceBase
  id: FoodJuniper
  components:
  - type: Sprite
    sprite: _Lua/Objects/Specific/Hydroponics/juniper.rsi
    state: produce
  - type: Item
    heldPrefix: produce
  - type: Material
  - type: PhysicalComposition
    materialComposition:
      FoodJuniper: 100
  - type: Stack
    stackType: FoodJuniper
    count: 1
  - type: Produce
    seedId: juniper
  - type: SolutionContainerManager
    solutions:
      food:
        maxVol: 10
        reagents:
        - ReagentId: Nutriment
          Quantity: 2
        - ReagentId: SalicylicAcid
          Quantity: 2