- type: job
  id: Valet
  name: job-name-valet
  description: job-description-valet
  playTimeTracker: JobValet
  salary: 35000 #Lua 25000<35000
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000 #Lua 10800<18000 (5 часов ~= 1-2 смены)
  startingGear: ValetGear
  alwaysUseSpawner: true
  icon: "JobIconBartender"
  supervisors: job-supervisors-sr
  weight: 60
  displayWeight: 40
  canBeAntag: false
  access:
  - Maintenance
  - External
  - Service
  - Frontier
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Nanotrasen

- type: startingGear
  id: ValetGear
  equipment:
    head: ClothingHeadHatBellhop
    gloves: ClothingHandsGlovesColorWhite
    id: ValetPDA
  storage:
    back:
    - ShipVoucherFrontierValet
  encryptionKeys:
  - EncryptionKeyGreeting
  - EncryptionKeyService

- type: chameleonOutfit
  id: ValetChameleonOutfit
  job: Valet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBellhop
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterVestValet
    gloves: ClothingHandsGlovesColorWhite
