// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaCorp
// See AGPLv3.txt for details.
using Content.Shared._Lua.Administration.ChunkMonitor;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using System.Linq;

namespace Content.Client._Lua.Administration.UI.ChunkMonitor;

[GenerateTypedNameReferences]
public sealed partial class ChunkMonitorWindow : DefaultWindow
{
    private const float AutoRefreshSeconds = 2f;
    public event Action<NetEntity>? MapSelected;
    public event Action<NetEntity>? RefreshPressed;
    public event Action<ChunkMonitorChunkInfo>? ChunkSelected;
    public event Action<NetEntity, ChunkMonitorChunkInfo>? DeleteSelectedPressed;
    public event Action<NetEntity, ChunkMonitorChunkInfo>? TeleportSelectedPressed;
    public event Action<NetEntity, ChunkMonitorChunkInfo>? PurgeSelectedPressed;
    private NetEntity _selectedMap = NetEntity.Invalid;
    private ChunkMonitorChunkInfo? _selectedChunk;
    private ChunkMonitorMapInfo[] _maps = [];
    private bool _suppressMapSelect;
    private float _autoRefreshTimer;
    private ChunkMonitorHeatmapMode _heatmapMode = ChunkMonitorHeatmapMode.Off;

    public ChunkMonitorWindow()
    {
        Title = Loc.GetString("chunk-monitor-title");
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ =>
        {
            if (_selectedMap.IsValid())
                RefreshPressed?.Invoke(_selectedMap);
        };
        MapDropdown.OnItemSelected += args =>
        {
            if (_suppressMapSelect)
                return;
            if (args.Id < 0 || args.Id >= _maps.Length)
                return;
            var map = _maps[args.Id].MapUid;
            _selectedMap = map;
            _selectedChunk = null;
            _autoRefreshTimer = 0f;
            MapControl.SetSelectedMap(map);
            ClearDetails();
            MapSelected?.Invoke(map);
        };
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-off"), (int) ChunkMonitorHeatmapMode.Off);
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-entities"), (int) ChunkMonitorHeatmapMode.Entities);
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-players"), (int) ChunkMonitorHeatmapMode.Players);
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-shuttles"), (int) ChunkMonitorHeatmapMode.Shuttles);
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-debris"), (int) ChunkMonitorHeatmapMode.Debris);
        HeatmapDropdown.AddItem(Loc.GetString("chunk-monitor-heatmap-grids"), (int) ChunkMonitorHeatmapMode.Grids);
        HeatmapDropdown.SelectId((int) ChunkMonitorHeatmapMode.Off);
        HeatmapDropdown.OnItemSelected += args =>
        {
            _heatmapMode = (ChunkMonitorHeatmapMode) args.Id;
            MapControl.SetHeatmapMode(_heatmapMode);
        };
        MapControl.ChunkClicked += coords =>
        {
            var info = MapControl.TryGetChunk(coords, out var found) ? found : (ChunkMonitorChunkInfo?) null;
            if (info == null)
                return;
            _selectedChunk = info.Value;
            ChunkSelected?.Invoke(info.Value);
        };
        DeleteButton.OnPressed += _ =>
        {
            if (!_selectedMap.IsValid() || _selectedChunk == null)
                return;
            DeleteSelectedPressed?.Invoke(_selectedMap, _selectedChunk.Value);
        };
        TeleportButton.OnPressed += _ =>
        {
            if (!_selectedMap.IsValid() || _selectedChunk == null)
                return;
            TeleportSelectedPressed?.Invoke(_selectedMap, _selectedChunk.Value);
        };
        PurgeButton.OnPressed += _ =>
        {
            if (!_selectedMap.IsValid() || _selectedChunk == null)
                return;
            PurgeSelectedPressed?.Invoke(_selectedMap, _selectedChunk.Value);
        };
        ClearDetails();
        SetCounts(0, 0, 0);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (!IsOpen || !_selectedMap.IsValid())
            return;
        _autoRefreshTimer += args.DeltaSeconds;
        if (_autoRefreshTimer < AutoRefreshSeconds)
            return;
        _autoRefreshTimer -= AutoRefreshSeconds;
        RefreshPressed?.Invoke(_selectedMap);
    }

    public void SetMaps(ChunkMonitorMapInfo[] maps, NetEntity selectedMap)
    {
        _maps = maps;
        _selectedMap = selectedMap;
        MapControl.SetSelectedMap(selectedMap);
        _suppressMapSelect = true;
        MapDropdown.Clear();
        for (var i = 0; i < maps.Length; i++)
        {
            MapDropdown.AddItem(maps[i].Name, i);
        }
        var selectedIndex = Array.FindIndex(maps, m => m.MapUid == selectedMap);
        if (selectedIndex < 0 && maps.Length > 0)
            selectedIndex = 0;
        if (selectedIndex >= 0)
            MapDropdown.SelectId(selectedIndex);
        _suppressMapSelect = false;
    }

    public void SetChunks(ChunkMonitorChunkInfo[] chunks)
    {
        MapControl.SetChunks(chunks);
        MapControl.SetHeatmapMode(_heatmapMode);
        if (_selectedChunk is { } selected)
        {
            var found = chunks.FirstOrDefault(c => c.Coordinates == selected.Coordinates);
            if (found != default)
            {
                _selectedChunk = found;
                SetDetails(found);
                SetSelectedChunk(found.Coordinates);
            }
            else
            {
                _selectedChunk = null;
                ClearDetails();
                SetSelectedChunk(null);
            }
        }
        else
        {
            SetSelectedChunk(null);
        }
    }

    public void SetSelectedChunk(Vector2i? coords)
    {
        MapControl.Selected = coords;
    }

    public void SetCounts(int loaded, int unloaded, int deleted)
    {
        SummaryLabel.Text = Loc.GetString("chunk-monitor-summary",
            ("loaded", loaded),
            ("unloaded", unloaded),
            ("deleted", deleted));
    }

    public void SetDetails(ChunkMonitorChunkInfo chunk)
    {
        CoordsLabel.Text = Loc.GetString("chunk-monitor-details-coords", ("x", chunk.Coordinates.X), ("y", chunk.Coordinates.Y));
        StatusLabel.Text = Loc.GetString("chunk-monitor-details-status", ("status", chunk.Status.ToString()));
        EntitiesLabel.Text = Loc.GetString("chunk-monitor-details-entities", ("count", chunk.EntityCount));
        PlayersLabel.Text = Loc.GetString("chunk-monitor-details-players", ("count", chunk.PlayerCount));
        ShuttlesLabel.Text = Loc.GetString("chunk-monitor-details-shuttles", ("count", chunk.ShuttleCount));
        StationsLabel.Text = Loc.GetString("chunk-monitor-details-stations", ("count", chunk.StationCount));
        DebrisLabel.Text = Loc.GetString("chunk-monitor-details-debris", ("count", chunk.DebrisCount));
        GridsLabel.Text = Loc.GetString("chunk-monitor-details-grids", ("count", chunk.GridCount));
        TeleportButton.Disabled = false;
        PurgeButton.Disabled = false;
        DeleteButton.Disabled = false;
    }

    public void ClearDetails()
    {
        CoordsLabel.Text = Loc.GetString("chunk-monitor-details-none");
        StatusLabel.Text = string.Empty;
        EntitiesLabel.Text = string.Empty;
        PlayersLabel.Text = string.Empty;
        ShuttlesLabel.Text = string.Empty;
        StationsLabel.Text = string.Empty;
        DebrisLabel.Text = string.Empty;
        GridsLabel.Text = string.Empty;
        TeleportButton.Disabled = true;
        PurgeButton.Disabled = true;
        DeleteButton.Disabled = true;
    }
}
