// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp Contributors
// See AGPLv3.txt for details.

using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Prototypes;
using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Disease.Components;
using Content.Shared._Lua.Disease.Events;
using Content.Shared._Lua.Disease.UI;
using Content.Shared.Backmen.Disease;

namespace Content.Client._Lua.Disease.UI;

[GenerateTypedNameReferences]
public sealed partial class DiseaseAnalyzerWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action? Analyze;
    public event Action? PrintReport;
    public event Action? Contain;
    public event Action? ClearSample;

    public DiseaseAnalyzerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AnalyzeButton.OnPressed += _ => Analyze?.Invoke();
        PrintReportButton.OnPressed += _ => PrintReport?.Invoke();
        ContainButton.OnPressed += _ => Contain?.Invoke();
        ClearButton.OnPressed += _ => ClearSample?.Invoke();
    }

    public void UpdateState(DiseaseAnalyzerWindowInterfaceState state)
    {
        UpdateSubstanceCode(state.Code);
        UpdateStatus(state.Status, state.Filled);
        UpdateButtons(state.Status, state.Filled, state.Fragile);
        UpdateDiseaseInfo(state.Status, state.Filled, state.DiseaseIDs);
    }

    public void UpdateProgress(DiseaseAnalyzerAnalyzeTimerUpdate message)
    {
        UpdateProgress(message.Progress);
    }

    private void UpdateProgress(float progress)
    {
        ProgressBar.Value = progress;
    }

    private void UpdateSubstanceCode(int code)
    {
        SubstanceCodeLabel.Text = code.ToString("X8");
    }

    private void UpdateStatus(DiseaseAnalyzerStatus status, bool filled)
    {
        if (status != DiseaseAnalyzerStatus.Analyzed && !filled)
        {
            StatusLabel.Text = Loc.GetString("disease-analyzer-status-not-filled");
            StatusLabel.FontColorOverride = Color.White;
            return;
        }

        var statusString = status switch
        {
            DiseaseAnalyzerStatus.NotAnalyzed => "disease-analyzer-status-not-analyzed",
            DiseaseAnalyzerStatus.Analyzing => "disease-analyzer-status-analyzing",
            DiseaseAnalyzerStatus.Analyzed => "disease-analyzer-status-analyzed",
            _ => "disease-analyzer-status-not-filled"
        };

        StatusLabel.Text = Loc.GetString(statusString);

        StatusLabel.FontColorOverride = status switch
        {
            DiseaseAnalyzerStatus.NotAnalyzed => Color.PaleVioletRed,
            DiseaseAnalyzerStatus.Analyzing => Color.Gold,
            DiseaseAnalyzerStatus.Analyzed => Color.DarkCyan,
            _ => Color.White
        };
    }

    private void UpdateButtons(DiseaseAnalyzerStatus status, bool filled, bool fragile)
    {
        if (status != DiseaseAnalyzerStatus.Analyzed && !filled)
        {
            AnalyzeButton.Disabled = true;
            PrintReportButton.Disabled = true;
            ContainButton.Disabled = true;
            ClearButton.Disabled = true;
            return;
        }

        var analyzing = status == DiseaseAnalyzerStatus.Analyzing;

        AnalyzeButton.Disabled = status != DiseaseAnalyzerStatus.NotAnalyzed;
        PrintReportButton.Disabled = status != DiseaseAnalyzerStatus.Analyzed;
        ClearButton.Disabled = analyzing;
        ContainButton.Disabled = !fragile || analyzing;
    }

    private void UpdateDiseaseInfo(DiseaseAnalyzerStatus status, bool filled, ProtoId<DiseasePrototype>[]? diseaseIDs)
    {
        DiseaseBox.RemoveAllChildren();

        DiseaseInfo.Visible = status == DiseaseAnalyzerStatus.Analyzed && filled;

        if (status != DiseaseAnalyzerStatus.Analyzed || !filled)
        {
            return;
        }

        if (diseaseIDs == null || diseaseIDs.Length == 0)
        {
            DiseaseFoundLabel.Text = Loc.GetString("disease-analyzer-no-diseases");
            DiseaseFoundLabel.FontColorOverride = Color.DarkCyan;
            return;
        }

        DiseaseFoundLabel.Text = Loc.GetString("disease-analyzer-diseases");
        DiseaseFoundLabel.FontColorOverride = Color.PaleVioletRed;

        foreach (var diseaseID in diseaseIDs)
        {
            if (_prototype.TryIndex(diseaseID, out var disease))
            {
                DiseaseBox.AddChild(new Label
                {
                    Text = $"- {Loc.GetString(disease.Name)}",
                });
            }
            else
            {
                DiseaseBox.AddChild(new Label
                {
                    Text = $"- {Loc.GetString("disease-analyzer-unknown-disease")}",
                });
            }
        }
    }
}
