# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: department
  id: OutpostSyndicate
  name: department-Outpost-Typan
  description: department-Outpost-Typan-description
  color: "#D381C9"
  weight: -9
  roles:
#  - OutpostTypanAtmosTech
#  - OutpostTypanBotanist
  - OutpostTypanCargotech
#  - OutpostTypanChef
#  - OutpostTypanMedic
#  - OutpostTypanRD
  - OutpostTypanScience
  - OutpostTypanTelecommunicationsOfficer
#  - OutpostTypanResearcher
  - OutpostSyndicateShareholder

- type: department
  id: LuaTech
  name: department-LuaTech
  description: department-LuaTech-description
  color: "#407DC4"
  weight: -9
  roles:
  - OpsLuaTech

- type: department
#  id: StormCreed
  id: Antag
  name: department-stormcreed
  description: department-stormcreed-description
  color: "#948471"
  weight: 60
  roles:
  - StormCreedCaptain
  - StormCreedFirstmate
  - StormCreedSoldier
