using Content.Client.UserInterface.Systems.Alerts.Controls;
using Content.Shared.Alert;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.UserInterface.Systems.Alerts.Widgets;

public enum AlertsLayoutMode // Lua
{
    Bottom,
    Right
}

/// <summary>
///     The status effects display on the right side of the screen.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AlertsUI : UIWidget
{
    // also known as Control.Children?
    private readonly Dictionary<AlertKey, AlertControl> _alertControls = new();
    private bool _showSprint;

    public AlertsLayoutMode LayoutMode { get; private set; } = AlertsLayoutMode.Bottom; // Lua

    public AlertsUI()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetLayoutMode(AlertsLayoutMode mode) // Lua
    {
        LayoutMode = mode;
        RightModeRoot.Visible = mode == AlertsLayoutMode.Right;
        BottomModeRoot.Visible = mode == AlertsLayoutMode.Bottom;
        ApplySprintVisibility();
        RebuildLayout(null);
    }

    public void SetIconScale(float scale)
    { foreach (var control in _alertControls.Values) { control.SetIconScale(scale); } }

    public void SetSprint(float value, bool visible)
    {
        _showSprint = visible;
        var clamped = Math.Clamp(value, 0f, 1f);
        RightSprintBar.Value = clamped;
        BottomSprintBar.Value = clamped;
        ApplySprintVisibility();
    }

    public void SyncControls(AlertsSystem alertsSystem,
        AlertOrderPrototype? alertOrderPrototype,
        IReadOnlyDictionary<AlertKey,
        AlertState> alertStates)
    {
        // remove any controls with keys no longer present
        if (SyncRemoveControls(alertStates))
            return;

        // now we know that alertControls contains alerts that should still exist but
        // may need to updated,
        // also there may be some new alerts we need to show.
        // further, we need to ensure they are ordered w.r.t their configured order
        SyncUpdateControls(alertsSystem, alertOrderPrototype, alertStates);
    }

    public void ClearAllControls()
    {
        foreach (var alertControl in _alertControls.Values)
        {
            alertControl.OnPressed -= AlertControlPressed;
            alertControl.Dispose();
        }

        _alertControls.Clear();
        LeftAlertContainer.Children.Clear();
        RightAlertContainer.Children.Clear();
        RightColumn1.Children.Clear(); // Lua
        RightColumn2.Children.Clear(); // Lua
        RightColumn3.Children.Clear(); // Lua
    }

    public event EventHandler<ProtoId<AlertPrototype>>? AlertPressed;

    private bool SyncRemoveControls(IReadOnlyDictionary<AlertKey, AlertState> alertStates)
    {
        var toRemove = new List<AlertKey>();
        foreach (var existingKey in _alertControls.Keys)
        {
            if (!alertStates.ContainsKey(existingKey))
                toRemove.Add(existingKey);
        }

        foreach (var alertKeyToRemove in toRemove)
        {
            _alertControls.Remove(alertKeyToRemove, out var control);
            if (control == null)
                return true;
            RemoveFromAllLayouts(control); // Lua
        }

        return false;
    }

    private void SyncUpdateControls(AlertsSystem alertsSystem, AlertOrderPrototype? alertOrderPrototype,
        IReadOnlyDictionary<AlertKey, AlertState> alertStates)
    {
        foreach (var (alertKey, alertState) in alertStates)
        {
            if (!alertKey.AlertType.HasValue)
            {
                Logger.WarningS("alert", "found alertkey without alerttype," +
                                         " alert keys should never be stored without an alerttype set: {0}", alertKey);
                continue;
            }

            var alertType = alertKey.AlertType.Value;
            if (!alertsSystem.TryGet(alertType, out var newAlert))
            {
                Logger.ErrorS("alert", "Unrecognized alertType {0}", alertType);
                continue;
            }

            if (_alertControls.TryGetValue(newAlert.AlertKey, out var existingAlertControl) &&
                existingAlertControl.Alert.ID == newAlert.ID)
            {
                // key is the same, simply update the existing control severity / cooldown
                existingAlertControl.SetSeverity(alertState.Severity);
                if (alertState.ShowCooldown)
                    existingAlertControl.Cooldown = alertState.Cooldown;
                else existingAlertControl.Cooldown = null;
            }
            else
            {
                if (existingAlertControl != null)
                {
                    RemoveFromAllLayouts(existingAlertControl); // Lua
                }

                // this is a new alert + alert key or just a different alert with the same
                // key, create the control and add it in the appropriate order
                var newAlertControl = CreateAlertControl(newAlert, alertState);

                _alertControls[newAlert.AlertKey] = newAlertControl;
            }
        }
        RebuildLayout(alertOrderPrototype);
    }

    private void RemoveFromAllLayouts(AlertControl control) // Lua
    {
        LeftAlertContainer.Children.Remove(control);
        RightAlertContainer.Children.Remove(control);
        RightColumn1.Children.Remove(control);
        RightColumn2.Children.Remove(control);
        RightColumn3.Children.Remove(control);
    }

    private void RebuildLayout(AlertOrderPrototype? alertOrderPrototype)
    {
        LeftAlertContainer.Children.Clear();
        RightAlertContainer.Children.Clear();
        RightColumn1.Children.Clear(); // Lua
        RightColumn2.Children.Clear(); // Lua
        RightColumn3.Children.Clear(); // Lua
        var controls = _alertControls.Values.ToList();
        controls.Sort((a, b) =>
        {
            if (alertOrderPrototype != null) return alertOrderPrototype.Compare(a.Alert, b.Alert);
            return string.Compare(a.Alert.ID, b.Alert.ID, StringComparison.OrdinalIgnoreCase);
        });
        switch (LayoutMode) // Lua
        {
            case AlertsLayoutMode.Bottom:
                for (var i = 0; i < controls.Count; i++)
                {
                    var control = controls[i];
                    if ((i & 1) == 0) RightAlertContainer.Children.Add(control);
                    else LeftAlertContainer.Children.Add(control);
                }
                break;
            case AlertsLayoutMode.Right: // Lua
                for (var i = 0; i < controls.Count; i++)
                {
                    // 1 2 3
                    // 4 5 6
                    // 7 8 9 shit
                    var column = i % 3;
                    var control = controls[i];
                    switch (column)
                    {
                        case 0:
                            RightColumn1.Children.Add(control);
                            break;
                        case 1:
                            RightColumn2.Children.Add(control);
                            break;
                        default:
                            RightColumn3.Children.Add(control);
                            break;
                    }
                }
                break;
        }
    }

    private void ApplySprintVisibility()
    {
        RightSprintBar.Visible = _showSprint && LayoutMode == AlertsLayoutMode.Right;
        BottomSprintBar.Visible = _showSprint && LayoutMode == AlertsLayoutMode.Bottom;
    }

    private AlertControl CreateAlertControl(AlertPrototype alert, AlertState alertState)
    {
        (TimeSpan, TimeSpan)? cooldown = null;
        if (alertState.ShowCooldown)
            cooldown = alertState.Cooldown;

        var alertControl = new AlertControl(alert, alertState.Severity)
        {
            Cooldown = cooldown
        };
        alertControl.OnPressed += AlertControlPressed;
        return alertControl;
    }

    private void AlertControlPressed(BaseButton.ButtonEventArgs args)
    {
        if (args.Button is not AlertControl control)
            return;

        if (args.Event.Function != EngineKeyFunctions.UIClick)
            return;

        AlertPressed?.Invoke(this, control.Alert.ID);
    }
}
