using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client._DV.Administration.UI;

[GenerateTypedNameReferences]
public sealed partial class DepartmentWhitelistPanel : PanelContainer
{
    public Action<ProtoId<JobPrototype>, bool>? OnSetJob;

    public DepartmentWhitelistPanel(DepartmentPrototype department, IPrototypeManager proto, HashSet<ProtoId<JobPrototype>> whitelists, bool globalWhitelist, HashSet<ProtoId<JobPrototype>> addedJobs) // Frontier: add globalWhitelist, addedJobs
    {
        RobustXamlLoader.Load(this);

        var anyValid = false;
        var allWhitelisted = true;
        var sortedRoles = department.Roles
            .Select(id => (Id: id, Proto: proto.Index(id))).Where(x => x.Proto.Whitelisted && !addedJobs.Contains(x.Id)).OrderBy(x => x.Proto.LocalizedName).ToList();
        foreach (var (id, jobProto) in sortedRoles)
        {
            var thisJob = id; // closure capturing funny
            anyValid = true;
            addedJobs.Add(id);

            var button = new CheckBox();
            button.Text = jobProto.LocalizedName;
            button.Pressed = whitelists.Contains(id) || globalWhitelist;
            button.OnPressed += _ => OnButtonPressed(thisJob, button, globalWhitelist); // Frontier: check global whitelist
            JobsContainer.AddChild(button);

            allWhitelisted &= button.Pressed;
        }

        if (!anyValid) // Frontier: hide checkbox set if no valid events
            Visible = false;  // Frontier

        Department.Text = Loc.GetString(department.Name);
        Department.Modulate = department.Color;
        Department.Pressed = allWhitelisted;
        Department.OnPressed += args => OnDepartmentPressed(department, proto, whitelists, globalWhitelist); // Frontier: check global whitelist
    }

    // Frontier: global whitelist handling
    private void OnButtonPressed(ProtoId<JobPrototype> thisJob, CheckBox button, bool globalWhitelist)
    {
        if (globalWhitelist)
            button.Pressed = true; // Force the button on.
        else
            OnSetJob?.Invoke(thisJob, button.Pressed);
    }

    private void OnDepartmentPressed(DepartmentPrototype department, IPrototypeManager proto, HashSet<ProtoId<JobPrototype>> whitelists, bool globalWhitelist)
    {
        // Frontier: global override
        if (globalWhitelist)
        {
            Department.Pressed = true;
            return;
        }
        // End Frontier: global override

        foreach (var id in department.Roles)
        {
            // only request to whitelist roles that aren't already whitelisted, and vice versa - Frontier: roles must be whitelisted
            if (whitelists.Contains(id) != Department.Pressed && proto.Index(id).Whitelisted)
                OnSetJob?.Invoke(id, Department.Pressed);
        }
    }
    // End Frontier
}
