// LuaWorld - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Client.Shuttles.UI;
using Content.Shared._Mono.Ships.Components;
using Content.Shared._NF.Shuttles.Components;
using Content.Shared._Lua.Stargate.Components;
using Content.Shared.Cargo.Components;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using System.Numerics;

namespace Content.Client._Lua.Stargate.UI;

[GenerateTypedNameReferences]
public sealed partial class StarGateLandingPickerControl : BaseShuttleControl
{
    [Dependency] private readonly IMapManager _mapManager = default!;
    protected override bool ScaleWithControlSize => true;
    public MapId TargetMapId = MapId.Nullspace;
    public NetEntity? ShuttleNetEntity;
    private Angle _angle;
    public event Action<MapCoordinates, Angle>? OnLocationPicked;
    private Vector2? _hoverPos;
    private readonly SharedTransformSystem _xform;
    private List<Entity<MapGridComponent>> _grids = new();
    private readonly HashSet<EntityUid> _wallEntities = new();
    private readonly HashSet<Entity<StargateComponent>> _blockedGates = new();
    private readonly HashSet<Entity<StargateConsoleComponent>> _blockedConsoles = new();
    private readonly List<(Vector2 Position, float Radius)> _blockedPoints = new();
    private readonly List<(EntityUid Uid, Matrix3x2 GridToWorld)> _blockedShuttleContours = new();
    private readonly List<Vector2> _landingWorldVerticesBuffer = new();
    private const float BeaconBlockRadiusTiles = 6f;
    private const float ConsoleBlockRadiusTiles = 8f;
    private const float GateBlockRadiusTiles = 8f;

    public StarGateLandingPickerControl() : base(16f, 128f, 64f)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xform = EntManager.System<SharedTransformSystem>();
    }

    private bool IsBlocked(Vector2 worldPos)
    {
        if (TryGetShuttlePreview(worldPos, out var shuttleUid, out var shuttleGrid, out var previewGridToWorld))
            return IsBlockedByShuttleContour(shuttleUid, shuttleGrid, previewGridToWorld) || IsBlockedByOtherShuttleContours(shuttleUid, shuttleGrid, previewGridToWorld);
        foreach (var blocked in _blockedPoints)
        { if (Vector2.Distance(worldPos, blocked.Position) <= blocked.Radius) return true; }
        return IsPointInsideOtherShuttleContours(worldPos);
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.UIClick && TargetMapId != MapId.Nullspace)
        {
            var worldPos = InverseMapPosition(args.RelativePixelPosition);
            if (IsBlocked(worldPos))
            {
                args.Handle();
                return;
            }
            OnLocationPicked?.Invoke(new MapCoordinates(worldPos, TargetMapId), _angle);
            args.Handle();
            return;
        }
        base.KeyBindUp(args);
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        _angle -= Angle.FromDegrees(15f) * args.Delta.Y;
        _angle = _angle.Reduced();
        args.Handle();
    }

    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        _hoverPos = InverseMapPosition(args.RelativePixelPosition);
        base.MouseMove(args);
    }

    protected override void MouseExited()
    {
        _hoverPos = null;
        base.MouseExited();
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);
        if (TargetMapId == MapId.Nullspace) return;
        DrawBacking(handle);
        DrawCenteredCircles(handle);
        var selectedToWorld = Matrix3Helpers.CreateTransform(Offset, Angle.Zero);
        var viewBoundsWorld = Matrix3Helpers.TransformBox(selectedToWorld, new Box2(-WorldRangeVector, WorldRangeVector));
        Matrix3x2.Invert(selectedToWorld, out var worldToSelected);
        var selectedToView = Matrix3x2.CreateScale(new Vector2(MinimapScale, -MinimapScale)) * Matrix3x2.CreateTranslation(MidPointVector);
        _grids.Clear();
        _mapManager.FindGridsIntersecting(TargetMapId, viewBoundsWorld, ref _grids);
        DrawWalls(handle, viewBoundsWorld, worldToSelected, selectedToView);
        _blockedPoints.Clear();
        _blockedGates.Clear();
        _blockedConsoles.Clear();
        _blockedShuttleContours.Clear();
        _blockedPoints.Add((Offset, BeaconBlockRadiusTiles));
        var beaconScreenPos = ScalePosition(new Vector2(0f, 0f));
        var beaconPxRadius = BeaconBlockRadiusTiles * MinimapScale;
        handle.DrawCircle(beaconScreenPos, beaconPxRadius, Color.Yellow.WithAlpha(0.10f));
        handle.DrawCircle(beaconScreenPos, beaconPxRadius, Color.Yellow, filled: false);
        var center = new MapCoordinates(Offset, TargetMapId);
        var gateLookupRange = WorldRange + GateBlockRadiusTiles;
        var consoleLookupRange = WorldRange + ConsoleBlockRadiusTiles;
        _lookup.GetEntitiesInRange(center, gateLookupRange, _blockedGates);
        _lookup.GetEntitiesInRange(center, consoleLookupRange, _blockedConsoles);
        foreach (var (uid, _) in _blockedGates)
        {
            var coords = _xform.GetMapCoordinates(uid);
            if (coords.MapId != TargetMapId) continue;
            _blockedPoints.Add((coords.Position, GateBlockRadiusTiles));
            var localPos = coords.Position - Offset;
            var screenPos = ScalePosition(new Vector2(localPos.X, -localPos.Y));
            var pxRadius = GateBlockRadiusTiles * MinimapScale;
            handle.DrawCircle(screenPos, pxRadius, Color.Red.WithAlpha(0.16f));
            handle.DrawCircle(screenPos, pxRadius, Color.Red, filled: false);
        }
        foreach (var (uid, _) in _blockedConsoles)
        {
            var coords = _xform.GetMapCoordinates(uid);
            if (coords.MapId != TargetMapId) continue;
            _blockedPoints.Add((coords.Position, ConsoleBlockRadiusTiles));
            var localPos = coords.Position - Offset;
            var screenPos = ScalePosition(new Vector2(localPos.X, -localPos.Y));
            var pxRadius = ConsoleBlockRadiusTiles * MinimapScale;
            var color = Color.OrangeRed;
            handle.DrawCircle(screenPos, pxRadius, color.WithAlpha(0.13f));
            handle.DrawCircle(screenPos, pxRadius, color, filled: false);
        }

        var selectedShuttleUid = EntityUid.Invalid;
        if (ShuttleNetEntity is { } selectedShuttleNet && EntManager.TryGetEntity(selectedShuttleNet, out var selectedShuttleMaybe) && selectedShuttleMaybe != null)
        { selectedShuttleUid = selectedShuttleMaybe.Value; }
        foreach (var grid in _grids)
        {
            var uid = grid.Owner;
            if (uid == selectedShuttleUid) continue;
            var isExplicitShuttle = EntManager.HasComponent<ShuttleFTLComponent>(uid) || EntManager.HasComponent<CrewedShuttleComponent>(uid) || EntManager.HasComponent<CargoShuttleComponent>(uid) || EntManager.HasComponent<IFFComponent>(uid);
            if (!isExplicitShuttle) continue;
            var shuttleCoords = _xform.GetMapCoordinates(uid);
            if (shuttleCoords.MapId != TargetMapId) continue;
            var gridToWorld = Matrix3Helpers.CreateTransform(_xform.GetWorldPosition(uid), _xform.GetWorldRotation(uid));
            _blockedShuttleContours.Add((uid, gridToWorld));
            var gridToView = gridToWorld * worldToSelected * selectedToView;
            var fill = Color.IndianRed.WithAlpha(0.18f);
            var border = Color.IndianRed.WithAlpha(0.95f);
            DrawGrid(handle, gridToView, grid, fill, border, 0.03f);
        }
        if (_hoverPos is { } pos)
        {
            var screenPos = ScalePosition(new Vector2(pos.X - Offset.X, -(pos.Y - Offset.Y)));
            var blocked = IsBlocked(pos);
            var crossColor = blocked ? Color.IndianRed : Color.LimeGreen;
            if (TryGetShuttlePreview(pos, out var shuttleUid, out var shuttleGrid, out var previewGridToWorld))
            {
                var previewGridToView = previewGridToWorld * worldToSelected * selectedToView;
                DrawGrid(handle, previewGridToView, (shuttleUid, shuttleGrid), crossColor.WithAlpha(0.20f), crossColor.WithAlpha(0.95f), 0.03f);
            }
            const float sz = 8f;
            handle.DrawLine(screenPos - new Vector2(sz, 0), screenPos + new Vector2(sz, 0), crossColor.WithAlpha(0.9f));
            handle.DrawLine(screenPos - new Vector2(0, sz), screenPos + new Vector2(0, sz), crossColor.WithAlpha(0.9f));
        }
    }
    private void DrawCenteredCircles(DrawingHandleScreen handle)
    {
        var origin = MidPointVector;
        var gridLines = Color.LightGray.WithAlpha(0.01f);
        const float EquatorialMultiplier = 2f;
        var minDistance = MathF.Pow(EquatorialMultiplier, EquatorialMultiplier * 1.5f);
        var maxDistance = MathF.Pow(2f, EquatorialMultiplier * 6f);
        var cornerDistance = MathF.Sqrt(WorldRange * WorldRange + WorldRange * WorldRange);
        for (var radius = minDistance; radius <= maxDistance; radius *= EquatorialMultiplier)
        {
            if (radius > cornerDistance) continue;
            var color = Color.ToSrgb(gridLines).WithAlpha(0.05f);
            var scaledRadius = MinimapScale * radius;
            var text = $"{radius:0}m";
            var textDimensions = handle.GetDimensions(Font, text, UIScale);
            handle.DrawCircle(origin, scaledRadius, color, false);
            handle.DrawString(Font, origin - new Vector2(0f, scaledRadius + textDimensions.Y), text, UIScale, color);
        }
        const int gridLinesRadial = 8;
        for (var i = 0; i < gridLinesRadial; i++)
        {
            Angle angle = (Math.PI / gridLinesRadial) * i;
            var aExtent = angle.ToVec() * ScaledMinimapRadius * 1.42f;
            var lineColor = Color.MediumSpringGreen.WithAlpha(0.02f);
            handle.DrawLine(origin - aExtent, origin + aExtent, lineColor);
        }
    }

    private void DrawWalls(DrawingHandleScreen handle, Box2 viewBoundsWorld, Matrix3x2 worldToSelected, Matrix3x2 selectedToView)
    {
        _wallEntities.Clear();
        foreach (var grid in _grids)
        {
            foreach (var entity in _lookup.GetEntitiesIntersecting(grid, viewBoundsWorld))
            {
                if (!EntManager.TryGetComponent<MetaDataComponent>(entity, out var meta) || meta.EntityPrototype == null) continue;
                if (!meta.EntityPrototype.ID.StartsWith("Wall")) continue;
                _wallEntities.Add(entity);
            }
        }
        if (_wallEntities.Count == 0) return;
        var worldToView = worldToSelected * selectedToView;
        var color = Color.WhiteSmoke.WithAlpha(0.9f);
        foreach (var uid in _wallEntities)
        {
            var aabb = _lookup.GetWorldAABB(uid);
            var p1 = Vector2.Transform(aabb.BottomLeft, worldToView);
            var p2 = Vector2.Transform(new Vector2(aabb.Right, aabb.Bottom), worldToView);
            var p3 = Vector2.Transform(aabb.TopRight, worldToView);
            var p4 = Vector2.Transform(new Vector2(aabb.Left, aabb.Top), worldToView);
            handle.DrawLine(p1, p2, color);
            handle.DrawLine(p2, p3, color);
            handle.DrawLine(p3, p4, color);
            handle.DrawLine(p4, p1, color);
        }
    }

    private bool TryGetShuttlePreview(Vector2 worldPos, out EntityUid shuttleUid, out MapGridComponent shuttleGrid, out Matrix3x2 previewGridToWorld)
    {
        shuttleUid = default;
        shuttleGrid = default!;
        previewGridToWorld = Matrix3x2.Identity;
        if (ShuttleNetEntity is not { } shuttleNet) return false;
        if (!EntManager.TryGetEntity(shuttleNet, out var shuttleUidNullable) || shuttleUidNullable == null) return false;
        shuttleUid = shuttleUidNullable.Value;
        if (!EntManager.TryGetComponent<MapGridComponent>(shuttleUid, out var shuttleGridNullable) || shuttleGridNullable == null) return false;
        shuttleGrid = shuttleGridNullable;
        var previewPos = worldPos;
        if (EntManager.TryGetComponent<PhysicsComponent>(shuttleUid, out var physicsNullable) && physicsNullable != null) previewPos -= _angle.RotateVec(physicsNullable.LocalCenter);
        previewGridToWorld = Matrix3Helpers.CreateTransform(previewPos, _angle);
        return true;
    }

    private bool IsBlockedByShuttleContour(EntityUid shuttleUid, MapGridComponent shuttleGrid, Matrix3x2 previewGridToWorld)
    {
        if (!GridData.TryGetValue(shuttleUid, out var gridData) || gridData.Vertices.Count < 3) return false;
        for (var i = 0; i + 2 < gridData.Vertices.Count; i += 3)
        {
            var a = Vector2.Transform(gridData.Vertices[i], previewGridToWorld);
            var b = Vector2.Transform(gridData.Vertices[i + 1], previewGridToWorld);
            var c = Vector2.Transform(gridData.Vertices[i + 2], previewGridToWorld);
            var triMin = Vector2.Min(a, Vector2.Min(b, c));
            var triMax = Vector2.Max(a, Vector2.Max(b, c));
            foreach (var blocked in _blockedPoints)
            {
                var radiusVec = new Vector2(blocked.Radius, blocked.Radius);
                var circleMin = blocked.Position - radiusVec;
                var circleMax = blocked.Position + radiusVec;
                if (triMax.X < circleMin.X || triMin.X > circleMax.X || triMax.Y < circleMin.Y || triMin.Y > circleMax.Y) continue;
                if (TriangleIntersectsCircle(a, b, c, blocked.Position, blocked.Radius)) return true;
            }
        }
        return false;
    }

    private bool IsBlockedByOtherShuttleContours(EntityUid landingShuttleUid, MapGridComponent shuttleGrid, Matrix3x2 previewGridToWorld)
    {
        if (!GridData.TryGetValue(landingShuttleUid, out var landingData) || landingData.Vertices.Count < 3) return false;
        _landingWorldVerticesBuffer.Clear();
        _landingWorldVerticesBuffer.Capacity = Math.Max(_landingWorldVerticesBuffer.Capacity, landingData.Vertices.Count);
        var landingMin = new Vector2(float.MaxValue, float.MaxValue);
        var landingMax = new Vector2(float.MinValue, float.MinValue);
        for (var i = 0; i < landingData.Vertices.Count; i++)
        {
            var transformed = Vector2.Transform(landingData.Vertices[i], previewGridToWorld);
            _landingWorldVerticesBuffer.Add(transformed);
            landingMin = Vector2.Min(landingMin, transformed);
            landingMax = Vector2.Max(landingMax, transformed);
        }
        var landingAabb = new Box2(landingMin, landingMax);
        foreach (var (otherUid, otherGridToWorld) in _blockedShuttleContours)
        {
            if (otherUid == landingShuttleUid) continue;
            if (!GridData.TryGetValue(otherUid, out var otherData) || otherData.Vertices.Count < 3) continue;
            var otherAabb = _lookup.GetWorldAABB(otherUid);
            if (!landingAabb.Intersects(otherAabb)) continue;
            for (var i = 0; i + 2 < landingData.Vertices.Count; i += 3)
            {
                var a1 = _landingWorldVerticesBuffer[i];
                var b1 = _landingWorldVerticesBuffer[i + 1];
                var c1 = _landingWorldVerticesBuffer[i + 2];
                for (var j = 0; j + 2 < otherData.Vertices.Count; j += 3)
                {
                    var a2 = Vector2.Transform(otherData.Vertices[j], otherGridToWorld);
                    var b2 = Vector2.Transform(otherData.Vertices[j + 1], otherGridToWorld);
                    var c2 = Vector2.Transform(otherData.Vertices[j + 2], otherGridToWorld);
                    if (TrianglesIntersect(a1, b1, c1, a2, b2, c2)) return true;
                }
            }
        }
        return false;
    }

    private bool IsPointInsideOtherShuttleContours(Vector2 worldPos)
    {
        foreach (var (otherUid, otherGridToWorld) in _blockedShuttleContours)
        {
            if (!GridData.TryGetValue(otherUid, out var otherData) || otherData.Vertices.Count < 3) continue;
            for (var j = 0; j + 2 < otherData.Vertices.Count; j += 3)
            {
                var a = Vector2.Transform(otherData.Vertices[j], otherGridToWorld);
                var b = Vector2.Transform(otherData.Vertices[j + 1], otherGridToWorld);
                var c = Vector2.Transform(otherData.Vertices[j + 2], otherGridToWorld);
                if (PointInTriangle(worldPos, a, b, c)) return true;
            }
        }
        return false;
    }

    private static bool TriangleIntersectsCircle(Vector2 a, Vector2 b, Vector2 c, Vector2 center, float radius)
    {
        var radiusSquared = radius * radius;
        if (Vector2.DistanceSquared(a, center) <= radiusSquared || Vector2.DistanceSquared(b, center) <= radiusSquared || Vector2.DistanceSquared(c, center) <= radiusSquared) return true;
        if (PointInTriangle(center, a, b, c)) return true;
        if (DistanceSquaredToSegment(center, a, b) <= radiusSquared || DistanceSquaredToSegment(center, b, c) <= radiusSquared || DistanceSquaredToSegment(center, c, a) <= radiusSquared) return true;
        return false;
    }

    private static bool PointInTriangle(Vector2 p, Vector2 a, Vector2 b, Vector2 c)
    {
        static float Sign(Vector2 p1, Vector2 p2, Vector2 p3)
        { return (p1.X - p3.X) * (p2.Y - p3.Y) - (p2.X - p3.X) * (p1.Y - p3.Y); }
        var d1 = Sign(p, a, b);
        var d2 = Sign(p, b, c);
        var d3 = Sign(p, c, a);
        var hasNeg = d1 < 0 || d2 < 0 || d3 < 0;
        var hasPos = d1 > 0 || d2 > 0 || d3 > 0;
        return !(hasNeg && hasPos);
    }

    private static bool TrianglesIntersect(Vector2 a1, Vector2 b1, Vector2 c1, Vector2 a2, Vector2 b2, Vector2 c2)
    {
        if (PointInTriangle(a1, a2, b2, c2)
            || PointInTriangle(b1, a2, b2, c2)
            || PointInTriangle(c1, a2, b2, c2)
            || PointInTriangle(a2, a1, b1, c1)
            || PointInTriangle(b2, a1, b1, c1)
            || PointInTriangle(c2, a1, b1, c1))
        { return true; }
        if (SegmentsIntersect(a1, b1, a2, b2)
            || SegmentsIntersect(a1, b1, b2, c2)
            || SegmentsIntersect(a1, b1, c2, a2)
            || SegmentsIntersect(b1, c1, a2, b2)
            || SegmentsIntersect(b1, c1, b2, c2)
            || SegmentsIntersect(b1, c1, c2, a2)
            || SegmentsIntersect(c1, a1, a2, b2)
            || SegmentsIntersect(c1, a1, b2, c2)
            || SegmentsIntersect(c1, a1, c2, a2))
        { return true; }
        return false;
    }

    private static bool SegmentsIntersect(Vector2 p1, Vector2 p2, Vector2 q1, Vector2 q2)
    {
        static float Cross(Vector2 a, Vector2 b) => a.X * b.Y - a.Y * b.X;
        static bool OnSegment(Vector2 a, Vector2 b, Vector2 p)
        {
            const float eps = 0.0001f;
            return p.X <= MathF.Max(a.X, b.X) + eps && p.X >= MathF.Min(a.X, b.X) - eps && p.Y <= MathF.Max(a.Y, b.Y) + eps && p.Y >= MathF.Min(a.Y, b.Y) - eps;
        }
        var r = p2 - p1;
        var s = q2 - q1;
        var rxs = Cross(r, s);
        var qpxr = Cross(q1 - p1, r);
        const float epsilon = 0.0001f;
        if (MathF.Abs(rxs) < epsilon && MathF.Abs(qpxr) < epsilon)
        { return OnSegment(p1, p2, q1) || OnSegment(p1, p2, q2) || OnSegment(q1, q2, p1) || OnSegment(q1, q2, p2); }
        if (MathF.Abs(rxs) < epsilon) return false;
        var t = Cross(q1 - p1, s) / rxs;
        var u = Cross(q1 - p1, r) / rxs;
        return t >= -epsilon && t <= 1f + epsilon && u >= -epsilon && u <= 1f + epsilon;
    }

    private static float DistanceSquaredToSegment(Vector2 point, Vector2 a, Vector2 b)
    {
        var ab = b - a;
        var abLenSquared = ab.LengthSquared();
        if (abLenSquared <= 0f) return Vector2.DistanceSquared(point, a);
        var t = Vector2.Dot(point - a, ab) / abLenSquared;
        t = Math.Clamp(t, 0f, 1f);
        var projection = a + ab * t;
        return Vector2.DistanceSquared(point, projection);
    }
}
