// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using System;
using System.Numerics;
using Content.Shared._Lua.Stargate.PlanetQuest;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Localization;
using Robust.Shared.Utility;

namespace Content.Client._Lua.Stargate.PlanetQuest;

[GenerateTypedNameReferences]
public sealed partial class PlanetQuestPanel : PanelContainer
{
    private const int DescriptionWidth = 290;
    private const int DescriptionMinHeight = 22;

    private bool _collapsed;

    public bool Dragging;
    public Vector2 DragOffset;

    private string? _lastQuestName;
    private string? _lastQuestDescription;
    private int _lastStructTotal;
    private int _lastStructDone;
    private int _lastBossTotal;
    private int _lastBossDone;
    private int _lastReward;
    private int _lastPlayers;
    private bool _lastCompleted;

    public PlanetQuestPanel()
    {
        RobustXamlLoader.Load(this);
        CollapseButton.OnPressed += _ => ToggleCollapse();

        DragHeader.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            Dragging = true;
            DragOffset = args.PointerLocation.Position / UIScale - Position;
            args.Handle();
        };

        DragHeader.OnKeyBindUp += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick)
                Dragging = false;
        };

        StructureLabel.Visible = false;
        BossLabel.Visible = false;

        DescriptionBox.SetWidth = DescriptionWidth;
        DescriptionLabel.SetWidth = DescriptionWidth;
    }

    private void ToggleCollapse()
    {
        _collapsed = !_collapsed;
        ContentContainer.Visible = !_collapsed;
        CollapseButton.Text = _collapsed ? "+" : "-";
    }

    public void UpdateQuest(PlanetQuestComponent quest)
    {
        if (quest.QuestName == _lastQuestName
            && quest.QuestDescription == _lastQuestDescription
            && quest.StructureTotalCount == _lastStructTotal
            && quest.StructureCompletedCount == _lastStructDone
            && quest.BossTotalCount == _lastBossTotal
            && quest.BossCompletedCount == _lastBossDone
            && quest.TotalReward == _lastReward
            && quest.ActivePlayerCount == _lastPlayers
            && quest.Completed == _lastCompleted)
            return;

        _lastQuestName = quest.QuestName;
        _lastQuestDescription = quest.QuestDescription;
        _lastStructTotal = quest.StructureTotalCount;
        _lastStructDone = quest.StructureCompletedCount;
        _lastBossTotal = quest.BossTotalCount;
        _lastBossDone = quest.BossCompletedCount;
        _lastReward = quest.TotalReward;
        _lastPlayers = quest.ActivePlayerCount;
        _lastCompleted = quest.Completed;

        if (!string.IsNullOrEmpty(quest.QuestName))
        {
            QuestNameLabel.Visible = true;
            QuestNameLabel.Text = Loc.GetString(quest.QuestName);
        }
        else
        {
            QuestNameLabel.Visible = false;
        }

        if (!string.IsNullOrEmpty(quest.QuestDescription))
        {
            DescriptionBox.Visible = true;
            var description = Loc.GetString(quest.QuestDescription);
            var msg = new FormattedMessage();
            msg.AddMarkupOrThrow($"[font size=8][color=#AAAAAA]{FormattedMessage.EscapeText(description)}[/color][/font]");
            DescriptionLabel.SetMessage(msg, tagsAllowed: null);

            DescriptionLabel.Measure(new Vector2(DescriptionWidth, float.PositiveInfinity));
            var height = Math.Max(DescriptionMinHeight, (int)MathF.Ceiling(DescriptionLabel.DesiredSize.Y));
            DescriptionBox.SetHeight = height;
            DescriptionLabel.SetHeight = height;
        }
        else
        {
            DescriptionBox.Visible = false;
        }

        if (quest.StructureTotalCount > 0)
        {
            StructureLabel.Visible = true;
            var done = quest.StructureCompletedCount >= quest.StructureTotalCount;
            StructureLabel.Text = done
                ? Loc.GetString("planet-quest-panel-structures-done")
                : Loc.GetString("planet-quest-panel-structures-progress", ("current", quest.StructureCompletedCount), ("total", quest.StructureTotalCount));
            StructureLabel.FontColorOverride = Robust.Shared.Maths.Color.FromHex(done ? "#55FF55" : "#FFDD44");
        }
        else
        {
            StructureLabel.Visible = false;
        }

        if (quest.BossTotalCount > 0)
        {
            BossLabel.Visible = true;
            var done = quest.BossCompletedCount >= quest.BossTotalCount;
            BossLabel.Text = done
                ? Loc.GetString("planet-quest-panel-target-done")
                : Loc.GetString("planet-quest-panel-target-progress", ("current", quest.BossCompletedCount), ("total", quest.BossTotalCount));
            BossLabel.FontColorOverride = Robust.Shared.Maths.Color.FromHex(done ? "#55FF55" : "#FFDD44");
        }
        else
        {
            BossLabel.Visible = false;
        }

        if (quest.ActivePlayerCount > 1 && quest.TotalReward > 0)
        {
            var perPlayer = quest.TotalReward / quest.ActivePlayerCount;
            RewardLabel.Text = Loc.GetString("planet-quest-panel-reward-split", ("perPlayer", perPlayer), ("total", quest.TotalReward), ("players", quest.ActivePlayerCount));
        }
        else
        {
            RewardLabel.Text = Loc.GetString("planet-quest-panel-reward-only", ("amount", quest.TotalReward));
        }
    }

}
