using Content.Client.UserInterface.Controls;
using Content.Shared.Cargo;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._NF.Bank; // Frontier
using Content.Shared._NF.Cargo.BUI; // Lua

namespace Content.Client.Cargo.UI;

[GenerateTypedNameReferences]
public sealed partial class CargoPalletMenu : FancyWindow
{
    public Action? SellRequested;
    public Action? AppraiseRequested;

    public CargoPalletMenu()
    {
        RobustXamlLoader.Load(this);
        SellButton.OnPressed += OnSellPressed;
        AppraiseButton.OnPressed += OnAppraisePressed;
    }

    public void SetAppraisal(int amount)
    {
        AppraisalLabel.Text = BankSystemExtensions.ToSpesoString(amount); // Frontier: custom speso formatting
    }

    // Lua start
    public void SetAppraisalBreakdown(int baseAmount, int consoleDelta, int dynamicDelta, int total)
    {
        if (total == 0 && baseAmount == 0)
        { AppraisalLabel.Text = "-"; return; }
        var baseText = BankSystemExtensions.ToSpesoString(baseAmount);
        var consoleText = BankSystemExtensions.ToSpesoString(Math.Abs(consoleDelta));
        var dynText = BankSystemExtensions.ToSpesoString(Math.Abs(dynamicDelta));
        var totalText = BankSystemExtensions.ToSpesoString(total);
        var consoleSign = consoleDelta >= 0 ? "+" : "-";
        var dynSign = dynamicDelta >= 0 ? "+" : "-";
        AppraisalLabel.Text = $"{baseText} {consoleSign} {consoleText} {dynSign} {dynText} = {totalText}";
    }
    public void SetCount(int count)
    {
        CountLabel.Text = count.ToString();
    }
    public void SetEnabled(bool enabled)
    {
        AppraiseButton.Disabled = !enabled;
        SellButton.Disabled = !enabled;
    }

    public void SetTaxEntries(List<PalletTaxEntry> entries)
    {
        if (TaxList == null) return;
        TaxList.DisposeAllChildren();
        foreach (var e in entries)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
            row.AddChild(new Label { Text = e.Name, HorizontalExpand = true });
            var perc = e.Percent >= 0 ? $"+{e.Percent}%" : $"{e.Percent}%";
            row.AddChild(new Label { Text = perc });
            TaxList.AddChild(row);
        }
    }
    // Lua end

    private void OnSellPressed(BaseButton.ButtonEventArgs obj)
    {
        SellRequested?.Invoke();
    }

    private void OnAppraisePressed(BaseButton.ButtonEventArgs obj)
    {
        AppraiseRequested?.Invoke();
    }
}
