- type: antag
  id: NFPirate
  name: job-name-sc-soldier
  antagonist: true
  setPreference: false
  objective: roles-antag-sc-soldier-objective

- type: antag
  id: NFPirateFirstMate
  name: job-name-sc-firstmate
  antagonist: true
  setPreference: false
  objective: roles-antag-sc-soldier-objective

- type: antag
  id: NFPirateCaptain
  name: job-name-sc-captain
  antagonist: true
  setPreference: false
  objective: roles-antag-sc-soldier-objective
