- type: dungeonConfig
  id: GateQuadBunker
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateQuad

  - !type:CorridorDunGen
    width: 3
    tile: FloorDark

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorDark
    contents: NFLavaBrigEntrance

  - !type:RoomEntranceDunGen
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFNanoTrasenFacilityWallmounts
    tile: FloorDark

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorDark

  - !type:JunctionDunGen
    width: 1
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#DE3A3A96"

- type: dungeonConfig
  id: GateLineOutpost
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateLine

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFSnowyLabsEntrance

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFSnowyLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSilver
    cornerWall: WallSilver
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#4cc7aa96"

- type: dungeonConfig
  id: GateCompactCache
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateCompact
    - GateTiny

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#D381C996"

- type: dungeonConfig
  id: GateScatteredLabs
  minCount: 2
  maxCount: 4
  minOffset: 30
  maxOffset: 60
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSalvageExperiment
    presets:
    - GateCompact
    - GateTiny

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: GateCrossBunker
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateCross

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#D381C996"

- type: dungeonConfig
  id: GateHookOutpost
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateHook

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFCaveFactoryWallMounts
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#ab803bff"

- type: dungeonConfig
  id: GateTeeLab
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSalvageExperiment
    presets:
    - GateTee

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: GateWideShelter
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateWide

  - !type:BoundaryWallDunGen
    wall: WallRock
    cornerWall: WallRock
    tile: FloorCaveDrought

  - !type:CornerClutterDunGen
    contents: NFMineshaftClutter

- type: dungeonConfig
  id: GateDoubleStack
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateDouble

  - !type:CorridorDunGen
    width: 3
    tile: FloorCaveDrought

  - !type:RoomEntranceDunGen
    tile: FloorCaveDrought
    contents: NFBaseWoodWall

  - !type:BoundaryWallDunGen
    wall: WallRock
    cornerWall: WallRock
    tile: FloorCaveDrought

  - !type:CornerClutterDunGen
    contents: NFMineshaftClutter

- type: dungeonConfig
  id: GateScatteredMixed
  minCount: 2
  maxCount: 4
  minOffset: 35
  maxOffset: 70
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateTiny
    - GateSmall
    - GateLine
    - GateQuad

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#D381C996"

- type: dungeonConfig
  id: GateHauntedOutpost
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFHaunted
    presets:
    - GateTiny
    - GateTinySmall
    - GateCompact

  - !type:WormCorridorDunGen
    width: 3
    tile: FloorCaveDrought

  - !type:CorridorClutterDunGen
    contents: HauntedClutter

  - !type:BoundaryWallDunGen
    tile: FloorCaveDrought
    wall: WallRock

- type: dungeonConfig
  id: GateLabRuins
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFSalvageExperiment
    presets:
    - GateTiny
    - GateCompact
    - GateSmall

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

- type: dungeonConfig
  id: GateLavaOutpost
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFLavaBrig
    presets:
    - GateTiny
    - GateCompact
    - GateSmall

  - !type:CorridorDunGen
    width: 3
    tile: FloorDark

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorDark
    contents: NFLavaBrigEntrance

  - !type:RoomEntranceDunGen
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorDark
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFNanoTrasenFacilityWallmounts
    tile: FloorDark

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorDark

  - !type:JunctionDunGen
    width: 1
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorDark
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#DE3A3A96"

- type: dungeonConfig
  id: GateCaveFactory
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFCaveFactory
    presets:
    - GateTiny
    - GateCompact
    - GateWide
    - GateSmall

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFCaveFactoryWallMounts
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#ab803bff"

- type: dungeonConfig
  id: GateMixed
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
      - NFHaunted
      - NFCaveFactory
    presets:
    - GateTiny
    - GateTinySmall
    - GateCompact
    - GateSmall

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#D381C996"

- type: dungeonConfig
  id: GateScatteredHooks
  minCount: 2
  maxCount: 3
  minOffset: 40
  maxOffset: 80
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - NFMineshaft
    presets:
    - GateHook
    - GateLine

  - !type:CorridorDunGen
    width: 3
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:RoomEntranceDunGen
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:EntranceFlankDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:ExternalWindowDunGen
    tile: FloorSteel
    contents: NFBaseWindow

  - !type:WallMountDunGen
    contents: NFScienceLabsWalls
    tile: FloorSteel

  - !type:BoundaryWallDunGen
    wall: WallSolid
    cornerWall: WallReinforced
    tile: FloorSteel

  - !type:JunctionDunGen
    width: 1
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:JunctionDunGen
    width: 3
    tile: FloorSteel
    contents: NFBaseAirlock

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:CornerClutterDunGen
    contents: NFBaseClutter

  - !type:CorridorDecalSkirtingDunGen
    cardinalDecals:
      South: BrickTileWhiteLineS
      East: BrickTileWhiteLineE
      North: BrickTileWhiteLineN
      West: BrickTileWhiteLineW
    cornerDecals:
      SouthEast: BrickTileWhiteCornerSe
      SouthWest: BrickTileWhiteCornerSw
      NorthEast: BrickTileWhiteCornerNe
      NorthWest: BrickTileWhiteCornerNw
    pocketDecals:
      SouthWest: BrickTileWhiteInnerSw
      SouthEast: BrickTileWhiteInnerSe
      NorthWest: BrickTileWhiteInnerNw
      NorthEast: BrickTileWhiteInnerNe
    color: "#D381C996"
