// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.
using Content.Shared._Lua.DonateShop;
using Content.Shared._Lua.SponsorLoadout;
using Content.Shared._NF.Bank;
using Content.Shared.FixedPoint;
using Content.Shared.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.CustomControls;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;
using System.Linq;

namespace Content.Client._Lua.DonateShop.UI;

[GenerateTypedNameReferences]
public sealed partial class DonateShopWindow : BaseWindow
{
    private const int DragHeaderHeight = 180;
    private const string TierCategoryPrefix = "UplinkVipTier";
    private static readonly Color ShareholderColor = Color.FromHex("#F05C29");
    private static readonly Color GodColor = Color.FromHex("#00FF4A");
    private static readonly Color RankColor = Color.FromHex("#FF0000");
    private static readonly StyleBoxFlat ButtonStyle = new()
    {
        BackgroundColor = Color.FromHex("#6E5127"),
        BorderColor = Color.FromHex("#A8823D"),
        BorderThickness = new Thickness(1f),
    };
    private static readonly StyleBoxFlat SelectedButtonStyle = new()
    {
        BackgroundColor = Color.FromHex("#8A6736"),
        BorderColor = Color.FromHex("#DDBA7A"),
        BorderThickness = new Thickness(1f),
    };

    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;
    public event Action<string>? OnBuyPressed;
    private Control _noSubOverlay = default!;
    private bool _canAccess;
    private Dictionary<ProtoId<CurrencyPrototype>, FixedPoint2> _balance = [];
    private List<ListingDataWithCostModifiers> _listings = [];
    private string _currentTierTab = string.Empty;
    private string _currentCategory = string.Empty;
    private int _bankBalance;
    private bool _hasBankBalance;
    private HashSet<string> _activeTierNames = [];
    public DonateShopWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Resizable = false;
        WindowTitle.Text = Loc.GetString("donate-shop-menu-title");
        DonateCloseButton.OnPressed += _ => Close();
        LayoutContainer.SetAnchorPreset(ItemsScroll, LayoutContainer.LayoutPreset.Wide);
        _noSubOverlay = BuildNoSubOverlay();
        ItemsAreaContainer.AddChild(_noSubOverlay);
        LayoutContainer.SetAnchorPreset(_noSubOverlay, LayoutContainer.LayoutPreset.Wide);
    }

    private Control BuildNoSubOverlay()
    {
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#140F0ACC") },
            MouseFilter = MouseFilterMode.Stop,
            Visible = false,
        };
        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 12,
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };
        vbox.AddChild(new Label
        {
            Text = "У ВАС НЕТ ПОДПИСКИ =(",
            FontColorOverride = Color.FromHex("#F3D8A2"),
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "LabelBig" },
        });
        vbox.AddChild(new Label
        {
            Text = "ИСПРАВЬТЕ ЭТО!",
            FontColorOverride = Color.FromHex("#CCCCCC"),
            HorizontalAlignment = HAlignment.Center,
        });
        var btn = new Button
        {
            Text = "КУПИТЬ ПОДПИСКУ",
            HorizontalAlignment = HAlignment.Center,
            MinWidth = 220,
            StyleBoxOverride = ButtonStyle,
        };
        btn.OnPressed += _ => _uriOpener.OpenUri(new Uri("https://boosty.to/luaworld"));
        vbox.AddChild(btn);
        panel.AddChild(vbox);
        return panel;
    }

    public void UpdateState(DonateShopStateMessage state)
    {
        string roleMarkup;
        if (state.ActiveTierNames.Count > 0)
        {
            var parts = new List<string>();
            foreach (var tierName in state.ActiveTierNames)
            {
                var color = GetTierColor(tierName);
                parts.Add($"[color={color.ToHex()}]{tierName}[/color]");
            }
            roleMarkup = string.Join(", ", parts);
        }
        else
        {
            var fallback = state.TierName;
            var fallbackColor = GetTierColor(fallback);
            roleMarkup = $"[color={fallbackColor.ToHex()}]{fallback}[/color]";
        }
        RoleLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("donate-shop-role-label", ("role", roleMarkup))));
        StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("donate-shop-status-label", ("status", state.SubscriptionStatus))));
        string bankAmount;
        if (state.HasBankBalance)
            bankAmount = BankSystemExtensions.ToSpesoString(state.BankBalance);
        else if (state.Balance.TryGetValue("Speso", out var speso))
            bankAmount = BankSystemExtensions.ToSpesoString((int) speso);
        else
            bankAmount = "0 $";

        var lunaAmount = FormatLunaAmount(state.LunaCoinBalance);

        BalanceLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            Loc.GetString("donate-shop-balance-label", ("balance", bankAmount), ("luna", lunaAmount))));
        LunaCoinLabel.Visible = false;
        LunaCoinLabel.SetMessage(FormattedMessage.Empty);
        if (!string.IsNullOrWhiteSpace(state.ErrorLocKey))
        {
            ErrorLabel.Visible = true;
            ErrorLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString(state.ErrorLocKey)));
        }
        else
        {
            ErrorLabel.Visible = false;
            ErrorLabel.SetMessage(FormattedMessage.Empty);
        }
        _canAccess = state.CanAccess;
        _balance = state.Balance;
        _bankBalance = state.BankBalance;
        _hasBankBalance = state.HasBankBalance;
        _activeTierNames = state.ActiveTierNames.ToHashSet(StringComparer.OrdinalIgnoreCase);
        _listings = state.Listings
            .OrderBy(listing => listing.Priority)
            .ThenBy(listing => listing.Cost.Values.Sum())
            .ToList();
        PopulateTierTabs();
        PopulateItemCategories();
        RebuildItemList();
        UpdateOverlayVisibility();
    }

    private void UpdateOverlayVisibility()
    {
        var ownsTier = false;
        foreach (var roleName in _activeTierNames)
        {
            if (TierNameToCategoryId.TryGetValue(roleName, out var catId) && catId == _currentTierTab)
            {
                ownsTier = true;
                break;
            }
        }
        _noSubOverlay.Visible = !ownsTier;
    }
    private bool IsTierCategory(string categoryId) => categoryId.StartsWith(TierCategoryPrefix, StringComparison.Ordinal);
    private static readonly (string Id, string Label)[] TierTabOrder =
    [
        ("UplinkVipTierShareholder", DonorGroups.Shareholder),
        ("UplinkVipTierGod",         DonorGroups.God),
        ("UplinkVipTierRank1",       DonorGroups.Rank1),
        ("UplinkVipTierRank2",       DonorGroups.Rank2),
        ("UplinkVipTierRank3",       DonorGroups.Rank3),
    ];
    private static readonly Dictionary<string, string> TierNameToCategoryId = new(StringComparer.OrdinalIgnoreCase)
    {
        [DonorGroups.Shareholder] = "UplinkVipTierShareholder",
        [DonorGroups.God]         = "UplinkVipTierGod",
        [DonorGroups.Rank1]       = "UplinkVipTierRank1",
        [DonorGroups.Rank2]       = "UplinkVipTierRank2",
        [DonorGroups.Rank3]       = "UplinkVipTierRank3",
    };
    private void PopulateTierTabs()
    {
        TierTabContainer.RemoveAllChildren();
        var presentTierIds = new HashSet<string>();
        foreach (var roleName in _activeTierNames)
        { if (TierNameToCategoryId.TryGetValue(roleName, out var catId)) presentTierIds.Add(catId); }
        presentTierIds.Add("UplinkVipTierShareholder");
        var tabs = TierTabOrder.Where(t => presentTierIds.Contains(t.Id)).ToList();
        if (tabs.All(t => t.Id != _currentTierTab)) _currentTierTab = tabs.FirstOrDefault().Id ?? string.Empty;
        var group = new ButtonGroup();
        foreach (var (id, label) in tabs) AddTierTabButton(group, id, label);
    }

    private void AddTierTabButton(ButtonGroup group, string tierId, string text)
    {
        var button = new DonateCategoryButton
        {
            CategoryId = tierId,
            Text = text,
            Group = group,
            ToggleMode = true,
            Pressed = tierId == _currentTierTab,
            StyleClasses = { "OpenBoth" },
            MinWidth = 80,
        };
        button.OnPressed += _ =>
        {
            _currentTierTab = button.CategoryId;
            _currentCategory = string.Empty;
            RefreshTierTabStyles();
            PopulateItemCategories();
            RebuildItemList();
            UpdateOverlayVisibility();
        };
        button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        TierTabContainer.AddChild(button);
    }

    private void RefreshTierTabStyles()
    {
        foreach (var child in TierTabContainer.Children)
        {
            if (child is not DonateCategoryButton button) continue;
            button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        }
    }
    private void PopulateItemCategories()
    {
        CategoryListContainer.RemoveAllChildren();
        var tierListings = _listings
            .Where(l => l.Categories.Any(c => c.ToString() == _currentTierTab))
            .ToList();
        var itemCategories = new List<StoreCategoryPrototype>();
        foreach (var listing in tierListings)
        {
            foreach (var cat in listing.Categories)
            {
                var id = cat.ToString();
                if (IsTierCategory(id)) continue;
                if (!_prototype.TryIndex(cat, out StoreCategoryPrototype? proto)) continue;
                if (itemCategories.All(x => x.ID != proto.ID)) itemCategories.Add(proto);
            }
        }
        itemCategories = itemCategories.OrderBy(c => c.Priority).ToList();
        CategoryPanel.Visible = itemCategories.Count > 0;
        if (itemCategories.All(c => c.ID != _currentCategory)) _currentCategory = itemCategories.FirstOrDefault()?.ID ?? string.Empty;
        var group = new ButtonGroup();
        foreach (var cat in itemCategories) AddCategoryButton(group, cat.ID, Loc.GetString(cat.Name));
    }

    private void AddCategoryButton(ButtonGroup group, string categoryId, string text)
    {
        var button = new DonateCategoryButton
        {
            CategoryId = categoryId,
            Text = text,
            Group = group,
            ToggleMode = true,
            Pressed = categoryId == _currentCategory,
            StyleClasses = { "OpenBoth" },
        };
        button.OnPressed += _ =>
        {
            _currentCategory = button.CategoryId;
            RefreshCategoryButtonStyles();
            RebuildItemList();
        };
        button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        CategoryListContainer.AddChild(button);
    }

    private void RefreshCategoryButtonStyles()
    {
        foreach (var child in CategoryListContainer.Children)
        {
            if (child is not DonateCategoryButton button) continue;
            button.StyleBoxOverride = button.Pressed ? SelectedButtonStyle : ButtonStyle;
        }
    }

    private void RebuildItemList()
    {
        ItemsContainer.RemoveAllChildren();
        var filtered = _listings
            .Where(ShouldShow)
            .ToList();
        foreach (var listing in filtered) AddItemEntry(listing, _canAccess, CanBuyListing(listing));
        if (filtered.Count == 0)
        {
            ItemsContainer.AddChild(new Label
            { Text = Loc.GetString("donate-shop-no-items"), });
        }
    }

    private bool ShouldShow(ListingDataWithCostModifiers listing)
    {
        if (!string.IsNullOrEmpty(_currentTierTab) && !listing.Categories.Any(c => c.ToString() == _currentTierTab)) return false;
        if (!string.IsNullOrEmpty(_currentCategory)) return listing.Categories.Any(c => c.ToString() == _currentCategory);
        return true;
    }

    private void AddItemEntry(ListingDataWithCostModifiers listing, bool canAccess, bool canBuy)
    {
        var name = ListingLocalisationHelpers.GetLocalisedNameOrEntityName(listing, _prototype);
        var desc = ListingLocalisationHelpers.GetLocalisedDescriptionOrEntityDescription(listing, _prototype);
        var iconTexture = GetListingIconTexture(listing);
        var wrapper = new PanelContainer();
        wrapper.PanelOverride = new StyleBoxFlat
        {
            BorderColor = Color.FromHex("#5D4631"),
            BorderThickness = new Thickness(1f),
            BackgroundColor = Color.FromHex("#1B1510")
        };
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(8f)
        };
        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        if (iconTexture != null)
        {
            content.AddChild(new TextureRect
            {
                Texture = iconTexture,
                MinSize = new Vector2(48f, 48f),
                MaxSize = new Vector2(48f, 48f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            });
        }
        var textColumn = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };
        header.AddChild(new Label
        {
            Text = name,
            HorizontalExpand = true,
        });
        var description = new RichTextLabel { HorizontalExpand = true };
        description.SetMessage(FormattedMessage.FromMarkupPermissive(desc));
        var actionRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };
        var costLabel = new Label
        {
            FontColorOverride = Color.FromHex("#DDBA7A"),
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center,
        };
        var stockInfo = GetStockInfo(listing);
        costLabel.Text = stockInfo.HasValue ? $"{GetCostString(listing.Cost)}  [{listing.PurchaseAmount}/{stockInfo.Value}]" : GetCostString(listing.Cost);
        if (stockInfo.HasValue && listing.PurchaseAmount >= stockInfo.Value) costLabel.FontColorOverride = Color.FromHex("#888888");
        actionRow.AddChild(costLabel);
        var buyButton = new Button
        {
            Text = Loc.GetString("donate-shop-buy"),
            HorizontalAlignment = HAlignment.Right,
            Disabled = !canAccess || !canBuy,
            StyleBoxOverride = ButtonStyle,
            MinWidth = 104,
        };
        buyButton.OnPressed += _ => OnBuyPressed?.Invoke(listing.ID);
        actionRow.AddChild(buyButton);
        textColumn.AddChild(header);
        textColumn.AddChild(description);
        textColumn.AddChild(actionRow);
        content.AddChild(textColumn);
        root.AddChild(content);
        wrapper.AddChild(root);
        ItemsContainer.AddChild(wrapper);
    }

    private bool CanBuyListing(ListingDataWithCostModifiers listing)
    {
        if (!_hasBankBalance) return listing.CanBuyWith(_balance);
        foreach (var (currency, amount) in listing.Cost)
        {
            if (currency == "Speso")
            {
                if (_bankBalance < (int) amount) return false;
                continue;
            }
            if (!_balance.TryGetValue(currency, out var balance) || balance < amount) return false;
        }
        return true;
    }

    private Texture? GetListingIconTexture(ListingDataWithCostModifiers listing)
    {
        var sprite = _entity.System<SpriteSystem>();
        if (listing.Icon != null) return sprite.Frame0(listing.Icon);
        if (listing.ProductEntity != null) return sprite.GetPrototypeIcon(listing.ProductEntity).Default;
        return null;
    }

    private static int? GetStockInfo(ListingDataWithCostModifiers listing) => listing.Stock is > 0 ? listing.Stock : null;

    private string GetCostString(IReadOnlyDictionary<ProtoId<CurrencyPrototype>, FixedPoint2> cost)
    {
        if (cost.Count == 0) return Loc.GetString("store-currency-free");
        return string.Join(" + ", cost.Select(entry => entry.Key.Id switch
        {
            "Speso" => BankSystemExtensions.ToSpesoString((int) entry.Value),
            "LunaCoin" => $"⏾{BankSystemExtensions.ToIndependentString((int) entry.Value)}",
            _ => BankSystemExtensions.ToIndependentString((int) entry.Value)
        }));
    }

    private static string FormatLunaAmount(long amount)
    {
        if (amount <= 0)
            return BankSystemExtensions.ToIndependentString(0);

        var clamped = amount > int.MaxValue ? int.MaxValue : (int) amount;
        return BankSystemExtensions.ToIndependentString(clamped);
    }

    private static Color GetTierColor(string tierName) =>
        tierName.ToLowerInvariant() switch
        {
            "акционер" or "shareholder" => ShareholderColor,
            "божество" or "god"         => GodColor,
            _                           => RankColor,
        };

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos) => relativeMousePos.Y <= DragHeaderHeight ? DragMode.Move : DragMode.None;

    private sealed class DonateCategoryButton : Button
    { public string CategoryId = string.Empty; }
}
