using Content.Client.Parallax;
using Content.Client.Research;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Research;
using Content.Shared.Access.Systems;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Numerics;

namespace Content.Client._NF.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleMenu : FancyWindow
{
    public Action<string>? OnTechnologyCardPressed;
    public Action? OnServerButtonPressed;

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IPlayerManager _player = default!;

    private readonly ResearchSystem _research;
    private readonly SpriteSystem _sprite;
    private readonly AccessReaderSystem _accessReader;
    private ParallaxControl _parallaxControl;

    /// <summary>
    /// The parallax prototype to use for the background. Configurable.
    /// </summary>
    public string ParallaxPrototype { get; set; } = "Default";

    /// <summary>
    /// Updates the parallax background to use a different prototype
    /// </summary>
    /// <param name="parallaxPrototype">The new parallax prototype to use</param>
    public void SetParallaxPrototype(string parallaxPrototype)
    {
        ParallaxPrototype = parallaxPrototype;
        if (_parallaxControl != null)
        {
            _parallaxControl.ParallaxPrototype = parallaxPrototype;
        }
    }

    /// <summary>
    /// Console entity
    /// </summary>
    public EntityUid Entity;

    /// <summary>
    /// Currently selected tech
    /// Exists for better UI refreshing
    /// </summary>
    public ProtoId<TechnologyPrototype>? CurrentTech;

    /// <summary>
    /// All technologies and their availability
    /// </summary>
    public Dictionary<string, ResearchAvailability> List = new();

    /// <summary>
    /// Cached research points
    /// </summary>
    public int Points = 0;

    /// <summary>
    /// Is tech currently being dragged
    /// </summary>
    private bool _draggin;
    private const float MinZoom = 0.25f;
    private const float MaxZoom = 2.0f;
    private const float ZoomStep = 1.1f;
    private const int TreePadding = 20;
    private Vector2 _offset = Vector2.Zero;
    private float _zoom = 1f;
    private bool _centeredOnce;
    private float _baseWidth;
    private float _baseHeight;
    private readonly Dictionary<string, FancyResearchConsoleItem> _techItems = new();
    private readonly Dictionary<string, Vector2> _basePositions = new();

    /// <summary>
    /// the distance between elements on the grid.
    /// </summary>
    private const int GridSize = 90;

    /// <summary>
    /// technology cards size.
    /// </summary>
    private const int CardSize = 64;

    private static readonly Vector2 DefaultCenterPosition = Vector2.Zero;
    private bool _pendingCenter;
    private Vector2 _pendingCenterWorldPos;
    private bool _pendingCenterResetZoom;
    private Vector2 _boundsMin = Vector2.Zero;
    private Vector2 _boundsMax = Vector2.Zero;
    private ProtoId<RndFactionPrototype>? _researchFaction;

    public FancyResearchConsoleMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _research = _entity.System<ResearchSystem>();
        _sprite = _entity.System<SpriteSystem>();
        _accessReader = _entity.System<AccessReaderSystem>();

        // Frontier: Initialize parallax background
        _parallaxControl = new ParallaxControl
        {
            ParallaxPrototype = ParallaxPrototype,
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        // Add the parallax control to the ResearchesContainer at the beginning (bottom layer)
        ResearchesContainer.AddChild(_parallaxControl);

        // Set the proper rendering order by adjusting positions in the parent's child list
        // Controls with a higher position value are drawn on top (foreground)
        // Make sure the parallax is at the bottom of the z-order (drawn first)
        _parallaxControl.SetPositionInParent(0);

        TechViewport.SetPositionInParent(1);
        RecenterButton.SetPositionInParent(2);

        // Set up event handlers
        ServerButton.OnPressed += _ => OnServerButtonPressed?.Invoke();
        DragContainer.OnKeyBindDown += OnKeybindDown;
        DragContainer.OnKeyBindUp += OnKeybindUp;
        RecenterButton.OnPressed += _ => Recenter();
        TechViewport.OnResized += TryApplyPendingCenter;
        OnResized += TryApplyPendingCenter;

        // Empty initialization
        UpdatePanels(List);
    }

    public void SetEntity(EntityUid entity)
        => Entity = entity;

    public void SetResearchFaction(string? faction)
    {
        if (faction != null) _researchFaction = (ProtoId<RndFactionPrototype>) faction;
        else _researchFaction = null;
    }

    public void UpdatePanels(Dictionary<string, ResearchAvailability> dict)
    {
        // Clear existing items
        DragContainer.RemoveAllChildren();
        _techItems.Clear();
        _basePositions.Clear();

        List = dict;
        var boundsMin = Vector2.Zero;
        var boundsMax = Vector2.Zero;
        var boundsSet = false;

        // Calculate bounds
        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);
            if (!_research.IsTechnologyFactionAllowed(_researchFaction, proto))
                continue;

            var effectivePosition = _research.GetTechnologyPosition(_researchFaction, proto);
            var position = new Vector2(GridSize * effectivePosition.X, GridSize * effectivePosition.Y);

            if (!boundsSet)
            {
                boundsMin = position;
                boundsMax = position;
                boundsSet = true;
            }
            else
            {
                boundsMin = Vector2.Min(boundsMin, position);
                boundsMax = Vector2.Max(boundsMax, position);
            }
        }

        if (boundsSet)
        {
            _boundsMin = boundsMin;
            _boundsMax = boundsMax;

            var padding = 200f;
            var size = _boundsMax - _boundsMin;
            _baseWidth = size.X + CardSize + padding;
            _baseHeight = size.Y + CardSize + padding;
        }

        // Add tech items
        foreach (var tech in List)
        {
            var proto = _prototype.Index<TechnologyPrototype>(tech.Key);
            if (!_research.IsTechnologyFactionAllowed(_researchFaction, proto))
                continue;

            var effectivePrerequisites = _research.GetTechnologyPrerequisites(_researchFaction, proto);
            var control = new FancyResearchConsoleItem(proto, effectivePrerequisites, _sprite, tech.Value);

            DragContainer.AddChild(control);

            // Position the tech item
            var uiPosition = GetTechPosition(proto);
            _techItems[tech.Key] = control;
            _basePositions[tech.Key] = uiPosition;

            LayoutContainer.SetPosition(control, uiPosition);
            control.SelectAction += SelectTech;
            control.IsSelected = tech.Key == CurrentTech;
        }

        ApplyCamera();
        if (!_centeredOnce)
        {
            QueueCenterOnWorld(DefaultCenterPosition, resetZoom: true);
            TryApplyPendingCenter();
            _centeredOnce = true;
        }
    }

    public void UpdateInformationPanel(int points)
    {
        Points = points;

        var amountMsg = new FormattedMessage();
        amountMsg.AddMarkupOrThrow(Loc.GetString("research-console-menu-research-points-text",
            ("points", points)));
        ResearchAmountLabel.SetMessage(amountMsg);

        if (!_entity.TryGetComponent(Entity, out TechnologyDatabaseComponent? database))
            return;

        TierDisplayContainer.RemoveAllChildren();
        foreach (var disciplineId in database.SupportedDisciplines)
        {
            var discipline = _prototype.Index<TechDisciplinePrototype>(disciplineId);
            if (!_research.IsDisciplineFactionAllowed(Entity, discipline))
                continue;

            var tier = _research.GetTierCompletionPercentage(Entity, database, discipline, _prototype);

            var texture = new TextureRect
            {
                TextureScale = new Vector2(2, 2),
                VerticalAlignment = VAlignment.Center
            };
            var label = new RichTextLabel();
            texture.Texture = _sprite.Frame0(discipline.Icon);
            label.SetMessage(Loc.GetString("research-console-tier-percentage", ("perc", tier)));

            var control = new BoxContainer
            {
                Children =
                {
                    texture,
                    label,
                    new Control
                    {
                        MinWidth = 10
                    }
                }
            };
            TierDisplayContainer.AddChild(control);
        }
    }

    #region Drag handle
    protected override void MouseMove(GUIMouseMoveEventArgs args)
    {
        base.MouseMove(args);

        if (!_draggin)
            return;

        _offset += args.Relative;
        ApplyCamera();
    }

    /// <summary>
    /// Raised when LMB is pressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindDown(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = true;
    }

    /// <summary>
    /// Raised when LMB is unpressed at <see cref="DragContainer"/>
    /// </summary>
    private void OnKeybindUp(GUIBoundKeyEventArgs args)
    {
        if (args.Function == EngineKeyFunctions.Use)
            _draggin = false;
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => _draggin ? DragMode.None : base.GetDragModeFor(relativeMousePos);
    #endregion

    /// <summary>
    /// Selects a tech prototype and opens info panel
    /// </summary>
    /// <param name="proto">Tech proto</param>
    /// <param name="availability">Tech availability</param>
    public void SelectTech(TechnologyPrototype proto, ResearchAvailability availability)
    {
        InfoContainer.RemoveAllChildren();
        if (!_player.LocalEntity.HasValue)
            return;

        // Update selection
        CurrentTech = proto.ID;

        // Update visual selection state
        foreach (var child in DragContainer.Children)
        {
            if (child is FancyResearchConsoleItem techItem)
            {
                techItem.IsSelected = techItem.Prototype.ID == CurrentTech;
            }
        }

        // Create and add info panel
        var control = new FancyTechnologyInfoPanel(proto, _researchFaction, _accessReader.IsAllowed(_player.LocalEntity.Value, Entity), availability, _sprite);
        control.BuyAction += args => OnTechnologyCardPressed?.Invoke(args.ID);
        InfoContainer.AddChild(control);
    }

    public void Recenter()
    {
        QueueCenterOnWorld(DefaultCenterPosition, resetZoom: true);
        TryApplyPendingCenter();
    }

    public override void Close()
    {
        base.Close();
        DragContainer.RemoveAllChildren();
        InfoContainer.RemoveAllChildren();
    }

    private sealed partial class DisciplineButton(TechDisciplinePrototype proto) : Button
    {
        public TechDisciplinePrototype Proto = proto;
    }

    protected override void MouseWheel(GUIMouseWheelEventArgs args)
    {
        base.MouseWheel(args);
        if (args.Delta.Y == 0) return;
        var mouseScreen = UserInterfaceManager.MousePositionScaled.Position * UIScale;
        var viewportLocal = mouseScreen - TechViewport.GlobalPixelPosition;
        if (viewportLocal.X < 0 || viewportLocal.Y < 0 ||
            viewportLocal.X > TechViewport.PixelWidth || viewportLocal.Y > TechViewport.PixelHeight)
            return;
        var oldZoom = _zoom;
        var zoomMultiplier = MathF.Pow(ZoomStep, args.Delta.Y);
        _zoom = Math.Clamp(_zoom * zoomMultiplier, MinZoom, MaxZoom);
        if (Math.Abs(_zoom - oldZoom) < 0.0001f)
            return;
        var worldBefore = (viewportLocal - _offset) / oldZoom;
        _offset = viewportLocal - worldBefore * _zoom;
        ApplyCamera();
        args.Handle();
    }

    private Vector2 GetTechPosition(TechnologyPrototype proto)
    {
        var position = _research.GetTechnologyPosition(_researchFaction, proto);
        return new Vector2(
            position.X * GridSize - _boundsMin.X + TreePadding,
            position.Y * GridSize - _boundsMin.Y + TreePadding
        );
    }

    private void QueueCenterOnWorld(Vector2 worldPosition, bool resetZoom)
    {
        _pendingCenter = true;
        _pendingCenterWorldPos = worldPosition;
        _pendingCenterResetZoom = resetZoom;
    }

    private void TryApplyPendingCenter()
    {
        if (!_pendingCenter)
            return;
        if (TechViewport.PixelWidth <= 0 || TechViewport.PixelHeight <= 0)
            return;
        _pendingCenter = false;
        var uiPosition = new Vector2(
            _pendingCenterWorldPos.X * GridSize - _boundsMin.X + TreePadding,
            _pendingCenterWorldPos.Y * GridSize - _boundsMin.Y + TreePadding
        ) + new Vector2(CardSize / 2f, CardSize / 2f);
        CenterOnPosition(uiPosition, _pendingCenterResetZoom);
    }

    private bool CenterOnPosition(Vector2 position, bool resetZoom)
    {
        if (resetZoom)
            _zoom = 1f;
        var viewportCenter = new Vector2(TechViewport.PixelWidth, TechViewport.PixelHeight) / 2f;
        _offset = viewportCenter - position * _zoom;
        ApplyCamera();
        return true;
    }

    private void ApplyCamera()
    {
        foreach (var (id, item) in _techItems)
        {
            if (!_basePositions.TryGetValue(id, out var basePos))
                continue;
            var scaledPosition = basePos * _zoom + _offset;
            LayoutContainer.SetPosition(item, scaledPosition);
            item.SetScale(_zoom);
        }
        DragContainer.SetWidth = Math.Max(_baseWidth * _zoom, TechViewport.PixelWidth);
        DragContainer.SetHeight = Math.Max(_baseHeight * _zoom, TechViewport.PixelHeight);
    }
}
