using Content.Client.Computer;
using Content.Client.Salvage.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._NF.Salvage.UI;

/// <summary>
/// Generic window for offering multiple selections with a timer.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class SalvageExpeditionWindow : FancyWindow,
    IComputerWindow<EmergencyConsoleBoundUserInterfaceState>
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public Action? OnFinishPressed;
    public Action? OnConfirmPressed;
    public Action? OnCancelPressed;

    public bool Claimed;
    public bool Queued;
    public TimeSpan NextOffer;
    private TimeSpan? _progression;
    private TimeSpan? _confirmDeadline;
    private bool _cancelArmed;
    private static readonly TimeSpan ConfirmTotalTime = TimeSpan.FromMinutes(3);

    /// <summary>
    /// Time between NextOffers
    /// </summary>
    public TimeSpan Cooldown;

    /// <summary>
    /// Time between Progressions
    /// </summary>
    public TimeSpan ProgressionCooldown;

    /// <summary>
    /// Secondary timer used for tracking active progress.
    /// </summary>
    public TimeSpan? Progression
    {
        get => _progression;
        set
        {
            if (_progression == value)
                return;

            _progression = value;

            if (value == null)
            {
                ProgressionBox.Visible = false;
            }
            else
            {
                ProgressionBox.Visible = true;
            }
        }
    }

    public SalvageExpeditionWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ProgressionBar.ForegroundStyleBoxOverride = new StyleBoxFlat(Color.FromHex("#C74EBD"));
        Finish.OnPressed += _ => OnFinishPressed?.Invoke();
        Confirm.OnPressed += _ => OnConfirmPressed?.Invoke();
        Cancel.OnPressed += _ =>
        {
            if (!_cancelArmed)
            {
                _cancelArmed = true;
                if (!Cancel.StyleClasses.Contains("Danger"))
                    Cancel.StyleClasses.Add("Danger");
                return;
            }

            _cancelArmed = false;
            Cancel.StyleClasses.Remove("Danger");
            OnCancelPressed?.Invoke();
        };
    }

    public void AddOption(OfferingWindowOption option)
    {
        Container.AddChild(option);
    }

    public void ClearOptions()
    {
        Container.DisposeAllChildren();
    }

    public void SetFinishDisabled(bool disabled)
    {
        Finish.Disabled = disabled;
    }

    public void SetConfirmDisabled(bool disabled)
    {
        Confirm.Disabled = disabled;
    }

    public void SetCancelDisabled(bool disabled)
    {
        Cancel.Disabled = disabled;
        if (disabled)
        {
            _cancelArmed = false;
            Cancel.StyleClasses.Remove("Danger");
        }
    }

    public void SetQueueStatus(int activeCount, int queuePosition, int queueTotal, bool isQueued)
    {
        ActiveCountValue.Text = activeCount.ToString();
        QueueCountValue.Text = isQueued ? $"{queuePosition}/{queueTotal}" : "-";
    }

    public void SetConfirmDeadline(TimeSpan? remaining)
    {
        if (remaining == null)
        {
            _confirmDeadline = null;
            ConfirmBox.Visible = false;
            return;
        }

        _confirmDeadline = _timing.CurTime + remaining.Value;
        ConfirmBox.Visible = true;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_progression != null)
        {
            var remaining = _progression.Value - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
            {
                ProgressionBar.Value = 1f;
                ProgressionText.Text = "00:00";
            }
            else
            {
                ProgressionBar.Value = 1f - (float)(remaining / ProgressionCooldown);
                ProgressionText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }

        if (_confirmDeadline != null)
        {
            var remaining = _confirmDeadline.Value - _timing.CurTime;
            if (remaining < TimeSpan.Zero)
            {
                ConfirmBar.Value = 1f;
                ConfirmText.Text = "00:00";
            }
            else
            {
                var ratio = (float)(remaining / ConfirmTotalTime);
                ConfirmBar.Value = 1f - Math.Clamp(ratio, 0f, 1f);
                ConfirmText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }

        if (Claimed || Queued)
        {
            NextOfferBar.Value = 1f;
            NextOfferText.Text = "00:00";
        }
        else
        {
            var remaining = NextOffer - _timing.CurTime;

            if (remaining < TimeSpan.Zero)
            {
                NextOfferBar.Value = 1f;
                NextOfferText.Text = "00:00";
            }
            else
            {
                NextOfferBar.Value = 1f - (float)(remaining / Cooldown);
                NextOfferText.Text = $"{remaining.Minutes:00}:{remaining.Seconds:00}";
            }
        }
    }
}
