# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: job
  id: StormCreedFirstmate
  name: job-name-sc-firstmate
  description: job-description-sc-firstmate
  playTimeTracker: JobStormCreedFirstmate
  requirements:
  - !type:RoleTimeRequirement
    role: JobStormCreedSoldier
    time: 36000 # 20h
  startingGear: SCFirstMateGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconNFPirateFirstMate"
  supervisors: job-supervisors-sc-firstmate
  weight: 20
  displayWeight: 20
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: AutoPirateFirstMate
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: FalseRecord
    - type: Company
      companyName: StormCreed
    - type: DisableSuitSensors
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SCFirstMateGear
  equipment:
    belt: ClothingBeltUtility
    pocket1: BaseStormCreedUplink10
  storage:
    back:
    - AppraisalTool

- type: chameleonOutfit
  id: SCFirstMateChameleonOutfit
  job: StormCreedFirstmate
