// LuaWorld/LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaWorld/LuaCorp
// See AGPLv3.txt for details.

using Content.Client.UserInterface.Controls;
using Content.Shared._Lua.Parking;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Shared.Localization;

namespace Content.Client._Lua.Parking.UI;

[GenerateTypedNameReferences]
public sealed partial class TrafficManagerTabletWindow : FancyWindow
{
    public event Action<TrafficManagerTabletAction, NetEntity>? OnAction;

    public TrafficManagerTabletWindow()
    {
        RobustXamlLoader.Load(this);
        RefreshButton.OnPressed += _ => OnAction?.Invoke(TrafficManagerTabletAction.Refresh, NetEntity.Invalid);
    }

    public void UpdateState(TrafficManagerTabletUiState state)
    {
        ErrorLabel.Visible = !state.Authorized;
        ErrorLabel.Text = state.Error ?? Loc.GetString("traffic-manager-tablet-error-unauthorized");
        EntriesContainer.RemoveAllChildren();
        if (!state.Authorized) return;
        foreach (var entry in state.Shuttles)
        { EntriesContainer.AddChild(BuildRow(entry)); }
    }

    private Control BuildRow(TrafficManagerTabletShuttleEntry entry)
    {
        var bgColor = entry.Status switch
        {
            TrafficManagerShuttleStatus.Green => Color.FromHex("#1f4d2b"),
            TrafficManagerShuttleStatus.Orange => Color.FromHex("#6b3f00"),
            TrafficManagerShuttleStatus.Red => Color.FromHex("#5b1f1f"),
            _ => Color.FromHex("#202020"),
        };
        bgColor.A = 0.65f;
        var panel = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = bgColor },
            HorizontalExpand = true,
        };
        var root = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true,
            Margin = new Thickness(6),
        };
        var top = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6
        };
        var time = new Label
        {
            Text = $"{entry.TimeRemainingSeconds / 60:D2}:{entry.TimeRemainingSeconds % 60:D2}",
            HorizontalAlignment = HAlignment.Right
        };
        var reset = new Button { Text = Loc.GetString("traffic-manager-tablet-button-reset") };
        reset.OnPressed += _ => OnAction?.Invoke(TrafficManagerTabletAction.ResetTimer, entry.Shuttle);
        var add = new Button { Text = Loc.GetString("traffic-manager-tablet-button-add-ten") };
        add.Disabled = entry.ExtraMinutes >= 50;
        add.OnPressed += _ => OnAction?.Invoke(TrafficManagerTabletAction.AddTenMinutes, entry.Shuttle);
        var fine = new Button { Text = Loc.GetString("traffic-manager-tablet-button-fine") };
        fine.Disabled = !entry.FinePending || entry.NeedsDisposal;
        fine.OnPressed += _ => OnAction?.Invoke(TrafficManagerTabletAction.Fine, entry.Shuttle);
        var sell = new Button { Text = Loc.GetString("traffic-manager-tablet-button-sell") };
        sell.Disabled = !entry.SellEnabled;
        sell.OnPressed += _ => OnAction?.Invoke(TrafficManagerTabletAction.Sell, entry.Shuttle);
        var buttons = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Right,
            SeparationOverride = 4
        };
        buttons.AddChild(reset);
        buttons.AddChild(add);
        buttons.AddChild(fine);
        buttons.AddChild(sell);
        var left = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            HorizontalExpand = true
        };
        left.AddChild(new Label { Text = entry.ShuttleName, HorizontalExpand = true });
        left.AddChild(new Label { Text = Loc.GetString("traffic-manager-tablet-owner", ("owner", entry.OwnerName)), HorizontalExpand = true });
        top.AddChild(left);
        top.AddChild(new Label { Text = Loc.GetString("traffic-manager-tablet-time-remaining", ("time", time.Text)), HorizontalAlignment = HAlignment.Right });
        top.AddChild(buttons);
        root.AddChild(top);
        if (entry.FinePending)
        {
            root.AddChild(new Label
            {
                Text = Loc.GetString("traffic-manager-tablet-needs-fine"),
                FontColorOverride = Color.FromHex("#ffcc66")
            });
        }
        if (entry.NeedsDisposal)
        {
            root.AddChild(new Label
            {
                Text = Loc.GetString("traffic-manager-tablet-needs-disposal"),
                FontColorOverride = Color.FromHex("#ff6666")
            });
        }
        panel.AddChild(root);
        return panel;
    }
}


