using Content.Client.Message;
using Content.Shared._Lua.StationRecords;
using Content.Shared.Roles;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes; // Frontier

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralStationRecordConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!; // Frontier

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<uint>? OnDeleted;
    public event Action<ProtoId<JobPrototype>>? OnJobAdd; // Frontier
    public event Action<ProtoId<JobPrototype>>? OnJobSubtract; // Frontier
    public event Action<string>? OnAdvertisementChanged; // Frontier
    public event Action? OnCaptainIdPressed;
    public event Action? OnTargetIdPressed;
    public event Action<ShipCrewRole>? OnAssignShipRole;
    public event Action<uint>? OnFireSelectedRecord;
    public event Action<string, ShipCrewRole>? OnSetShipRoleByName;
    public event Action<string>? OnFireShipCrewByName;
    public const int MaxAdvertisementLength = 500; // Frontier
    private bool _isPopulating;
    private StationRecordFilterType _currentFilterType;
    private uint? _selectedKey; // Lua
    private string? _selectedRosterName; // Lua
    private bool _hasAuthorizedCaptain; // Lua
    private bool _hasTargetId; // Lua
    private bool _hasCaptainId; // Lua

    public GeneralStationRecordConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Frontier

        _currentFilterType = StationRecordFilterType.Name;

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            StationRecordsFilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        RecordListing.OnItemSelected += args =>
        {
            if (_isPopulating || RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            if (!_isPopulating)
                OnKeySelected?.Invoke(null);
        };

        StationRecordsFilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType) eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords();
            }
        };

        StationRecordsFiltersValue.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        StationRecordsFilters.OnPressed += _ =>
        {
            FilterListingOfRecords(StationRecordsFiltersValue.Text);
        };

        StationRecordsFiltersReset.OnPressed += _ =>
        {
            StationRecordsFiltersValue.Text = "";
            FilterListingOfRecords();
        };
        foreach (var role in Enum.GetValues<ShipCrewRole>())
        { ShipRoleOption.AddItem(Loc.GetString(ShipCrewManagement.GetRoleLocKey(role)), (int)role); }
        ShipRoleOption.SelectId(0);
        ShipRoleOption.OnItemSelected += args => ShipRoleOption.SelectId(args.Id);
        CaptainIdButton.OnPressed += _ => OnCaptainIdPressed?.Invoke();
        TargetIdButton.OnPressed += _ => OnTargetIdPressed?.Invoke();
        AssignRoleButton.OnPressed += _ =>
        {
            var role = (ShipCrewRole) ShipRoleOption.SelectedId;
            if (_hasAuthorizedCaptain && _hasTargetId)
            {
                OnAssignShipRole?.Invoke(role);
                return;
            }
            if (_hasAuthorizedCaptain && _selectedRosterName != null) OnSetShipRoleByName?.Invoke(_selectedRosterName, role);
        };
        FireSelectedButton.OnPressed += _ =>
        {
            if (_hasAuthorizedCaptain && _selectedRosterName != null)
            {
                OnFireShipCrewByName?.Invoke(_selectedRosterName);
                return;
            }
            if (_selectedKey is { } key) OnFireSelectedRecord?.Invoke(key);
        };

        ShipCrewRosterList.OnItemSelected += args =>
        {
            if (ShipCrewRosterList[args.ItemIndex].Metadata is string name) _selectedRosterName = name;
            UpdateShipCrewButtons();
        };
        ShipCrewRosterList.OnItemDeselected += _ =>
        {
            _selectedRosterName = null;
            UpdateShipCrewButtons();
        };
    }

    public void UpdateState(GeneralStationRecordConsoleState state)
    {
        _selectedKey = state.SelectedKey;
        UpdateShipCrewUi(state);
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != StationRecordsFiltersValue.Text)
            {
                StationRecordsFiltersValue.Text = state.Filter.Value;
            }
        }

        StationRecordsFilterType.SelectId((int)_currentFilterType);

        if (state.RecordListing == null)
        {
            RecordListingStatus.Visible = true;
            RecordListing.Visible = true;
            RecordListingStatus.Text = Loc.GetString("general-station-record-console-empty-state");
            RecordContainer.Visible = true;
            RecordContainerStatus.Visible = true;
            return;
        }

        RecordListingStatus.Visible = false;
        RecordListing.Visible = true;
        RecordContainer.Visible = true;
        PopulateRecordListing(state.RecordListing!, state.SelectedKey);

        RecordContainerStatus.Visible = state.Record == null;

        if (state.Record != null)
        {
            RecordContainerStatus.Visible = state.SelectedKey == null;
            RecordContainerStatus.Text = state.SelectedKey == null
                ? Loc.GetString("general-station-record-console-no-record-found")
                : Loc.GetString("general-station-record-console-select-record-info");
            PopulateRecordContainer(state.Record, state.CanDeleteEntries, state.SelectedKey);
        }
        else
        {
            RecordContainer.RemoveAllChildren();
        }
    }

    private void UpdateShipCrewUi(GeneralStationRecordConsoleState state)
    {
        _hasCaptainId = state.IsCaptainIdPresent;
        _hasAuthorizedCaptain = !string.IsNullOrEmpty(state.CaptainShipName);
        _hasTargetId = state.IsTargetIdPresent;
        CaptainIdButton.Text = state.IsCaptainIdPresent ? Loc.GetString("ship-crew-console-id-present") : Loc.GetString("ship-crew-console-id-missing");
        TargetIdButton.Text = state.IsTargetIdPresent ? Loc.GetString("ship-crew-console-id-present") : Loc.GetString("ship-crew-console-id-missing");
        CaptainIdLabel.Text = state.CaptainIdName ?? string.Empty;
        TargetIdLabel.Text = state.TargetIdName ?? string.Empty;
        CaptainIdLabel.Visible = state.IsCaptainIdPresent;
        TargetIdLabel.Visible = state.IsTargetIdPresent;
        if (!string.IsNullOrEmpty(state.TargetAssignedShipName) && !string.IsNullOrEmpty(state.TargetAssignedRoleLocKey))
        {
            TargetAssignmentLabel.Visible = true;
            TargetAssignmentLabel.SetMarkup(Loc.GetString("ship-crew-console-target-assignment", ("ship", state.TargetAssignedShipName), ("role", Loc.GetString(state.TargetAssignedRoleLocKey))));
        }
        else
        {
            TargetAssignmentLabel.Visible = false;
            TargetAssignmentLabel.Text = string.Empty;
        }
        CaptainShipLabel.Visible = !string.IsNullOrEmpty(state.CaptainShipName);
        if (CaptainShipLabel.Visible) CaptainShipLabel.SetMarkup(Loc.GetString("ship-crew-console-captain-ship", ("ship", state.CaptainShipName!)));
        ShipCrewRosterList.Clear();
        ShipCrewRosterList.ClearSelected();
        _selectedRosterName = null;
        if (state.ShipCrewRoster is { Count: > 0 })
        {
            foreach (var entry in state.ShipCrewRoster)
            {
                var item = ShipCrewRosterList.AddItem($"{entry.Name} — {Loc.GetString(ShipCrewManagement.GetRoleLocKey(entry.Role))}");
                item.Metadata = entry.Name;
            }
        }
        UpdateShipCrewButtons();
    }

    private void UpdateShipCrewButtons()
    {
        var canAssign = _hasAuthorizedCaptain && ((_hasCaptainId && _hasTargetId) || _selectedRosterName != null);
        AssignRoleButton.Disabled = !canAssign;
        var canFire = _hasAuthorizedCaptain && (_selectedRosterName != null || _selectedKey != null);
        FireSelectedButton.Disabled = !canFire;
    }
    private void PopulateRecordListing(Dictionary<uint, string> listing, uint? selected)
    {
        RecordListing.Clear();
        RecordListing.ClearSelected();

        _isPopulating = true;

        foreach (var (key, name) in listing)
        {
            var item = RecordListing.AddItem(name);
            item.Metadata = key;
            item.Selected = key == selected;
        }

        _isPopulating = false;

        RecordListing.SortItemsByText();
    }

    private void PopulateRecordContainer(GeneralStationRecord record, bool enableDelete, uint? id)
    {
        RecordContainer.RemoveAllChildren();
        var newRecord = new GeneralRecord(record, enableDelete, id);
        newRecord.OnDeletePressed = OnDeleted;

        RecordContainer.AddChild(newRecord);
    }

    private void FilterListingOfRecords(string text = "")
    {
        if (!_isPopulating)
        {
            OnFiltersChanged?.Invoke(_currentFilterType, text);
        }
    }

    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"general-station-record-{type.ToString().ToLower()}-filter");
    }
}
