// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2025 LuaCorp
// See AGPLv3.txt for details.
using Content.Shared._Lua.Administration.AdminStats;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Lua.Administration.UI.AdminStats;

[GenerateTypedNameReferences]
public sealed partial class AdminStatsWindow : DefaultWindow
{
    private const float ResourceInterval = 0.5f;
    private const float FullInterval = 30f;

    private float _resourceTimer;
    private float _fullTimer;

    public event Action? OnFullRefresh;
    public event Action? OnResourceRefresh;

    private static readonly StyleBoxFlat CardStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E1E2E"),
        ContentMarginLeftOverride = 0,
        ContentMarginRightOverride = 0,
        ContentMarginTopOverride = 0,
        ContentMarginBottomOverride = 0,
    };

    public AdminStatsWindow()
    {
        RobustXamlLoader.Load(this);
        NpcPanel.PanelOverride = CardStyle;
        ShuttlesPanel.PanelOverride = CardStyle;
        DebrisPanel.PanelOverride = CardStyle;
        PlayersPanel.PanelOverride = CardStyle;
        StargatePanel.PanelOverride = CardStyle;
        ResourcesPanel.PanelOverride = CardStyle;
    }

    public void UpdateFullState(AdminStatsEuiState state)
    {
        NpcActiveLabel.Text = state.NpcActive.ToString();
        NpcSleepingLabel.Text = state.NpcSleeping.ToString();
        NpcTotalLabel.Text = state.NpcTotal.ToString();

        ShuttlesActiveLabel.Text = state.ShuttlesActive.ToString();
        ShuttlesPausedLabel.Text = state.ShuttlesPaused.ToString();
        ShuttlesTotalLabel.Text = state.ShuttlesTotal.ToString();

        DebrisCountLabel.Text = state.DebrisCount.ToString();
        WrecksCountLabel.Text = state.WrecksCount.ToString();
        DebrisTotalLabel.Text = state.DebrisTotalCount.ToString();

        PlayersAliveLabel.Text = state.PlayersAlive.ToString();
        PlayersDeadLabel.Text = state.PlayersDead.ToString();
        PlayersInCryoLabel.Text = state.PlayersInCryo.ToString();

        StargateMapsActiveLabel.Text = state.StargateMapsActive.ToString();
        StargateMapsFrozenLabel.Text = state.StargateMapsFrozen.ToString();
        StargateMapsToLabel.Text = state.StargateMapsTotal.ToString();

        UpdateResources(state);
    }

    public void UpdateResources(AdminStatsEuiState state)
    {
        if (!state.IsLinuxHost)
        {
            RamLabel.Text = "NaN — unsupported OS";
            RamBar.Value = 0;
            CpuLabel.Text = $"NaN — unsupported OS ({state.CpuCount} cores)";
            CpuBar.Value = 0;
            return;
        }

        var ramUsedGb = state.RamUsedBytes / (1024.0 * 1024.0 * 1024.0);
        var ramTotalGb = state.RamTotalBytes / (1024.0 * 1024.0 * 1024.0);
        RamLabel.Text = $"{ramUsedGb:F2} / {ramTotalGb:F1} GB";
        var ramPercent = ramTotalGb > 0 ? ramUsedGb / ramTotalGb * 100.0 : 0;
        RamBar.Value = (float) ramPercent;
        var cpuClamped = Math.Clamp(state.CpuPercent, 0, 100);
        CpuLabel.Text = $"{cpuClamped:F1}% ({state.CpuCount} cores)";
        CpuBar.Value = (float) cpuClamped;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _resourceTimer += args.DeltaSeconds;
        _fullTimer += args.DeltaSeconds;
        if (_resourceTimer >= ResourceInterval)
        {
            _resourceTimer -= ResourceInterval;
            OnResourceRefresh?.Invoke();
        }
        if (_fullTimer >= FullInterval)
        {
            _fullTimer -= FullInterval;
            OnFullRefresh?.Invoke();
        }
    }
}
