// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Shared._Lua.Company;
using Content.Shared.Ghost;
using Content.Shared._Mono.Company;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using System.Numerics;

namespace Content.Client._Lua.Company.UI;

[GenerateTypedNameReferences]
public sealed partial class CompanyFactionsWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototypes = default!;
    [Dependency] private readonly IResourceCache _cache = default!;
    [Dependency] private readonly IPlayerManager _players = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private CompanyClientSystem _system = default!;
    private string? _selectedCompanyId;
    public string? SelectedCompanyId => _selectedCompanyId;
    private NetEntity? _selectedMember;
    private bool _viewerIsLeader;
    private string _viewerCompanyId = "None";
    private ButtonGroup _companyButtonGroup = new(false);
    private readonly Dictionary<string, ContainerButton> _companyButtons = new();
    private Texture _lockIcon = default!;
    private Texture _unlockIcon = default!;

    public CompanyFactionsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _system = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<CompanyClientSystem>();
        _lockIcon = _cache.GetResource<TextureResource>("/Textures/Interface/VerbIcons/lock.svg.192dpi.png").Texture;
        _unlockIcon = _cache.GetResource<TextureResource>("/Textures/Interface/VerbIcons/unlock.svg.192dpi.png").Texture;

        MembersList.OnItemSelected += args =>
        {
            if (MembersList[args.ItemIndex].Metadata is NetEntity ent) _selectedMember = ent;
            else _selectedMember = null;
            UpdateButtons();
        };

        JoinButton.OnPressed += _ =>
        { if (_selectedCompanyId != null) _system.RequestSetCompany(_selectedCompanyId); };
        LeaveButton.OnPressed += _ => _system.RequestSetCompany("None");
        KickButton.OnPressed += _ =>
        {
            if (_selectedCompanyId == null || _selectedMember == null) return;
            _system.RequestKick(_selectedCompanyId, _selectedMember.Value);
        };
        PopulateCompanies();
    }

    private string GetLocalCompanyId()
    {
        if (_players.LocalEntity is not { } player) return "None";
        if (!_entManager.TryGetComponent<CompanyComponent>(player, out var comp)) return "None";
        return string.IsNullOrWhiteSpace(comp.CompanyName) ? "None" : comp.CompanyName;
    }

    private void PopulateCompanies()
    {
        CompanyOptionsList.RemoveAllChildren();
        _companyButtons.Clear();
        _companyButtonGroup = new ButtonGroup(false);
        _selectedCompanyId = null;
        MembersList.Clear();
        var myCompany = GetLocalCompanyId();
        var companies = _prototypes.EnumeratePrototypes<CompanyPrototype>().Where(c => c.ID != "None").ToList();
        companies.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.OrdinalIgnoreCase));
        string? firstVisibleCompanyId = null;
        foreach (var company in companies)
        {
            if (company.HiddenFromNonMembers && !string.Equals(company.ID, myCompany, StringComparison.OrdinalIgnoreCase)) continue;
            firstVisibleCompanyId ??= company.ID;
            AddCompanyEntry(company);
        }
        if (firstVisibleCompanyId != null) SelectCompany(firstVisibleCompanyId);
    }

    private void AddCompanyEntry(CompanyPrototype company)
    {
        var wrapper = new ContainerButton
        { HorizontalExpand = true };
        wrapper.AddStyleClass(ContainerButton.StyleClassButton);
        wrapper.Group = _companyButtonGroup;
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 6
        };
        var icon = new TextureRect
        {
            CanShrink = true,
            MinSize = new Vector2(18, 18),
            Stretch = TextureRect.StretchMode.Scale,
            Texture = company.Disabled ? _lockIcon : _unlockIcon,
            VerticalAlignment = VAlignment.Center
        };
        var name = new Label
        {
            Text = company.Name,
            MinWidth = 50,
            HorizontalExpand = true,
            FontColorOverride = company.Color
        };
        header.AddChild(icon);
        header.AddChild(name);
        wrapper.AddChild(header);
        wrapper.OnButtonDown += _ => SelectCompany(company.ID);
        CompanyOptionsList.AddChild(wrapper);
        _companyButtons[company.ID] = wrapper;
    }

    private void SelectCompany(string companyId)
    {
        _selectedCompanyId = companyId;
        if (_companyButtons.TryGetValue(companyId, out var button) && !button.Pressed) button.Pressed = true;
        var display = companyId;
        if (_prototypes.TryIndex<CompanyPrototype>(companyId, out var proto)) display = proto.Name;
        MembersTitle.Text = Loc.GetString("company-factions-members-title-selected", ("company", display));
        MembersList.Clear();
        _selectedMember = null;
        _viewerIsLeader = false;
        _viewerCompanyId = GetLocalCompanyId();
        UpdateButtons();
        _system.RequestMembers(companyId);
    }

    public void UpdateMembers(string companyId, List<CompanyMemberEntry> members, bool viewerIsLeader, string viewerCompanyId)
    {
        if (_selectedCompanyId == null || !string.Equals(_selectedCompanyId, companyId, StringComparison.OrdinalIgnoreCase)) return;
        MembersList.Clear();
        foreach (var entry in members)
        { MembersList.AddItem(entry.Name, metadata: entry.Entity); }
        _viewerIsLeader = viewerIsLeader;
        _viewerCompanyId = viewerCompanyId;
        UpdateButtons();
    }

    private void UpdateButtons()
    {
        var selectedCompany = _selectedCompanyId;
        if (selectedCompany == null)
        {
            JoinButton.Visible = false;
            LeaveButton.Visible = false;
            KickButton.Visible = false;
            return;
        }
        var isPublic = _prototypes.TryIndex<CompanyPrototype>(selectedCompany, out var proto) && !proto.Disabled;
        var isPrivate = !isPublic;
        JoinButton.Visible = isPublic && !string.Equals(_viewerCompanyId, selectedCompany, StringComparison.OrdinalIgnoreCase);
        LeaveButton.Visible = isPublic && string.Equals(_viewerCompanyId, selectedCompany, StringComparison.OrdinalIgnoreCase);
        JoinButton.Disabled = false;
        LeaveButton.Disabled = false;
        if (_players.LocalEntity is { } self && _entManager.HasComponent<GhostComponent>(self))
        {
            JoinButton.Disabled = true;
            LeaveButton.Disabled = true;
        }
        KickButton.Visible = isPrivate && _viewerIsLeader && string.Equals(_viewerCompanyId, selectedCompany, StringComparison.OrdinalIgnoreCase);
        var selfNet = _players.LocalEntity is { } selfEnt ? _entManager.GetNetEntity(selfEnt) : NetEntity.Invalid;
        KickButton.Disabled = _selectedMember == null || (_selectedMember != null && _selectedMember.Value == selfNet);
    }
}

