// LuaCorp - This file is licensed under AGPLv3
// Copyright (c) 2026 LuaCorp
// See AGPLv3.txt for details.

using Content.Shared._Lua.Memorial;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Robust.Shared.Utility;

namespace Content.Client._Lua.Memorial;

[GenerateTypedNameReferences]
public sealed partial class MemorialDisplayWindow : BaseWindow
{
    private const int DragHeaderHeight = 28;
    private const float FallbackEntryWidth = 560f;

    public MemorialDisplayWindow()
    {
        RobustXamlLoader.Load(this);
        Resizable = false;
        CloseButton.OnPressed += _ => Close();
        EntriesContainer.OnResized += UpdateEntryWrapWidth;
    }

    public void UpdateState(MemorialDisplayUiState state)
    {
        DisplayTitle.Text = state.DisplayName;
        DisplayDescription.SetMessage(FormattedMessage.FromMarkupPermissive(state.DisplayDescription));
        EntriesContainer.RemoveAllChildren();
        foreach (var entry in state.Entries)
        {
            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                MaxWidth = FallbackEntryWidth,
            };
            label.SetMessage(FormattedMessage.FromMarkupPermissive(entry));
            EntriesContainer.AddChild(label);
        }

        UpdateEntryWrapWidth();
    }

    private void UpdateEntryWrapWidth()
    {
        var width = EntriesContainer.Width > 1 ? EntriesContainer.Width : FallbackEntryWidth;

        foreach (var child in EntriesContainer.Children)
        {
            if (child is RichTextLabel label)
                label.MaxWidth = width;
        }
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return relativeMousePos.Y <= DragHeaderHeight ? DragMode.Move : DragMode.None;
    }
}
