using Robust.Shared.ContentPack;
using Robust.Shared.IoC;
using Robust.Shared.Log;
using Robust.Shared.Utility;
using Serilog.Events;
using System.IO;
using System.Text.RegularExpressions;

namespace Content.Server._Lua.Networking;

public sealed class DecryptFailLogger : ILogHandler, IDisposable
{
    [Dependency] private readonly ILogManager _logManager = default!;
    [Dependency] private readonly IResourceManager _res = default!;
    private static readonly ResPath LogPath = new("/decryptfail.log");
    private static readonly ResPath IptablesPath = new("/decryptfail_iptables.sh");
    private static readonly Regex DecryptBanRegex = new(@"^\[DECRYPTBAN\] (?<ip>[\d.:a-fA-F]+) ", RegexOptions.Compiled);
    private readonly HashSet<string> _seenIps = new();
    private TextWriter? _logWriter;
    private TextWriter? _iptablesWriter;
    private ISawmill _sawmill = default!;

    public void Initialize()
    {
        _sawmill = Logger.GetSawmill("decryptfail");
        EnsureIptablesHeader();
        LoadSeenIps();
        OpenWriters();
        _logManager.GetSawmill("auth").AddHandler(this);
    }

    void ILogHandler.Log(string sawmillName, LogEvent message)
    {
        if (message.Level < LogEventLevel.Warning) return;
        var text = message.RenderMessage();
        var match = DecryptBanRegex.Match(text);
        if (!match.Success) return;
        var ip = match.Groups["ip"].Value;
        var timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
        _logWriter?.WriteLine($"[{timestamp}] {text}");
        _logWriter?.Flush();
        if (_seenIps.Add(ip))
        {
            _iptablesWriter?.WriteLine($"iptables -A INPUT -s {ip} -j DROP  # first seen {timestamp}");
            _iptablesWriter?.Flush();
        }
    }

    public void Dispose()
    {
        _logManager.GetSawmill("net").RemoveHandler(this);
        _logWriter?.Dispose();
        _iptablesWriter?.Dispose();
    }

    private void OpenWriters()
    {
        try
        { _logWriter = TextWriter.Synchronized(new StreamWriter(_res.UserData.Open(LogPath, FileMode.Append, FileAccess.Write, FileShare.Read), System.Text.Encoding.UTF8)); }
        catch (Exception e)
        { _sawmill.Error($"Failed to open {LogPath}: {e.Message}"); }
        try
        { _iptablesWriter = TextWriter.Synchronized(new StreamWriter(_res.UserData.Open(IptablesPath, FileMode.Append, FileAccess.Write, FileShare.Read), System.Text.Encoding.UTF8)); }
        catch (Exception e)
        { _sawmill.Error($"Failed to open {IptablesPath}: {e.Message}"); }
    }

    private void EnsureIptablesHeader()
    {
        if (_res.UserData.Exists(IptablesPath)) return;
        try
        {
            using var stream = _res.UserData.Open(IptablesPath, FileMode.CreateNew, FileAccess.Write, FileShare.Read);
            using var writer = new StreamWriter(stream);
            writer.WriteLine("#!/bin/bash");
            writer.WriteLine("# Auto-generated by DecryptFailLogger.");
            writer.WriteLine("# Run as root to block offending IPs: sudo bash decryptfail_iptables.sh");
            writer.WriteLine($"# Created: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        }
        catch (Exception e)
        { _sawmill.Error($"Failed to create {IptablesPath}: {e.Message}"); }
    }

    private void LoadSeenIps()
    {
        if (!_res.UserData.Exists(IptablesPath)) return;
        try
        {
            using var stream = _res.UserData.Open(IptablesPath, FileMode.Open, FileAccess.Read, FileShare.Read);
            using var reader = new StreamReader(stream);
            while (reader.ReadLine() is { } line)
            {
                var m = Regex.Match(line, @"iptables -A INPUT -s (?<ip>[\d.:a-fA-F]+) -j DROP");
                if (m.Success) _seenIps.Add(m.Groups["ip"].Value);
            }
        }
        catch (Exception e)
        { _sawmill.Error($"Failed to read existing {IptablesPath}: {e.Message}"); }
    }
}
