- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  salary: 50000 #Lua 65000<50000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: JobSeniorOfficer
    time: 36000 # 10h
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  canBeAntag: false
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Brigmedic
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: startingGear
  id: BailiffGear
  equipment:
#    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: HoloprojectorNfsd
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ #Lua 35 -> 9x19
    - Magazine9x19mmPistolRubber #Lua 35 -> 9x19
    - BaseSecurityUplinkRadioOfficer
    - ShipVoucherNfsdBailiff
    - RubberStampBailiff

- type: chameleonOutfit
  id: BailiffChameleonOutfit
  job: Bailiff
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterCoatNfsdFormal
    neck: ClothingNeckNfsdBadgeWarden
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdCream
    shoes: ClothingShoesBootsNfsdCreamFilled
