- type: job
  id: Cadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: JobSecurityCadet
  salary: 30000 #Lua 35000<30000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: JobPilot
    time: 36000 # 10h
#    - !type:OverallPlaytimeRequirement # comment from _Lua
#      time: 21600 # 6 hours
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 64800 # 18 hours
#      inverted: true # Leave slots open for newer, less confident players.
  startingGear: SDBaseLuaGear #Lua CadetGear<SDBaseLuaGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: startingGear
  id: CadetGear
  equipment:
#    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: BookSecurity
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ #Lua 35 -> 9x19
    - Magazine9x19mmPistolRubber #Lua 35 -> 9x19
    - FrontierUplinkCoin10

- type: chameleonOutfit
  id: CadetChameleonOutfit
  job: Cadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurityCadet
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled

