- type: job
  id: Deputy
  name: job-name-deputy
  description: job-description-deputy
  playTimeTracker: JobSecurityOfficer
  salary: 40000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: JobSecurityCadet
    time: 36000 # 10h
#    - !type:OverallPlaytimeRequirement # comment from _Lua
#      time: 43200 # 12 hours
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 21600 # 6 hours
#  alternateRequirementSets:
#    longerPlaytimeLessSec:
#    - !type:OverallPlaytimeRequirement
#      time: 360000 # 100 hours
#    - !type:RoleTimeRequirement
#      role: JobSecurityGuard
#      time: 21600 # 6 hours as security guard
  startingGear: SDBaseLuaGear #Lua DeputyGear<SDBaseLuaGear
  icon: JobIconDeputy
  supervisors: job-supervisors-sergeant
  weight: 130
  displayWeight: 40
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: startingGear
  id: DeputyGear
#  equipment:
#    pocket1: NFWeaponPistolUniversalNfsdLessLethal
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ #Lua 35 -> 9x19
    - Magazine9x19mmPistolRubber #Lua 35 -> 9x19
    - FrontierUplinkCoin10

- type: chameleonOutfit
  id: DeputyChameleonOutfit
  job: Deputy
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurity
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled
