- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  salary: 50000
  requirements:
  - !type:RoleTimeRequirement #Lua
    role: JobBrigmedic
    time: 18000 # 10h
  - !type:RoleTimeRequirement #Lua
    role: JobNfsdEngineer
    time: 18000 # 10h
#    - !type:OverallPlaytimeRequirement # comment from _Lua
#      time: 108000 # 30 hours
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 64800 # 18 hours
#    - !type:RoleTimeRequirement
#      role: JobSecurityOfficer
#      time: 43200 # 12 hours
#  alternateRequirementSets:
#    longerPlaytimeLessSec:
#    - !type:OverallPlaytimeRequirement
#      time: 540000 # 150 hours
#    - !type:RoleTimeRequirement
#      role: JobSecurityOfficer
#      time: 21600 # 6 hours
  startingGear: SeniorOfficerGear
  icon: JobIconSergeant
  supervisors: job-supervisors-bailiff
  weight: 140
  displayWeight: 50
  canBeAntag: false
  access:
  - Sergeant
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift
  - !type:AddComponentSpecial
    components:
      - type: Company
        companyName: Security

- type: startingGear
  id: SeniorOfficerGear
#  equipment:
#    pocket1: NFWeaponPistolUniversalNfsdLessLethal
  storage:
    back:
    - Flash
    - Magazine9x19mmPistolFMJ #Lua 35 -> 9x19
    - Magazine9x19mmPistolRubber #Lua 35 -> 9x19
    - BaseSecurityUplinkRadioOfficer
    - ShipVoucherNfsdSergeant

- type: chameleonOutfit
  id: SeniorOfficerChameleonOutfit
  job: SeniorOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSeniorOfficer
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled
